export const schema = {
  label: "Businesses",
  description: "Each business entity you own or have an ownership interest in. Used for QBI deduction, SE tax, home office, vehicle, and retirement plan calculations.",
  groups: [
    {
      label: "Business Entities",
      type: "list",
      key: "businesses",
      addLabel: "Add Business",
      itemLabel: "Business",
      description: "Add one entry per business. The name here must match the business_name in the Income section.",
      source: "Your Schedule C, K-1s, or entity formation documents.",
      itemGroups: [
        {
          label: "Identity",
          fields: [
            {
              key: "name",
              label: "Business Name",
              type: "text",
              description: "The legal or DBA name of the business. Must match your Income section entry.",
              source: "Your Schedule C Line A, or the business name on your K-1.",
            },
            {
              key: "ein",
              label: "EIN",
              type: "ein",
              description: "Employer Identification Number. Sole proprietors without employees can use their SSN instead.",
              source: "Your IRS EIN confirmation letter (CP-575) or prior tax return.",
            },
            {
              key: "entity_type",
              label: "Entity Type",
              type: "select",
              options: [
                { value: "sole_prop", label: "Sole Proprietorship" },
                { value: "llc_single", label: "Single-Member LLC" },
                { value: "llc_multi", label: "Multi-Member LLC" },
                { value: "s_corp", label: "S Corporation" },
                { value: "c_corp", label: "C Corporation" },
                { value: "partnership", label: "Partnership" },
                { value: "lp", label: "Limited Partnership" },
                { value: "llp", label: "Limited Liability Partnership" },
              ],
              description: "The legal structure of the entity. Determines how income, SE tax, and QBI deduction are calculated.",
              source: "Your state formation documents (Articles of Organization, etc.) or ask your CPA.",
            },
            {
              key: "tax_classification",
              label: "Tax Classification",
              type: "select",
              options: [
                { value: "disregarded", label: "Disregarded Entity (Schedule C)" },
                { value: "partnership", label: "Partnership (Form 1065)" },
                { value: "s_corp", label: "S Corporation (Form 1120-S)" },
                { value: "c_corp", label: "C Corporation (Form 1120)" },
              ],
              description: "How the IRS treats the entity for tax purposes. An LLC can elect to be taxed as an S-Corp even if formed as an LLC.",
              source: "Your Form 2553 (S-Corp election) or IRS Form 8832 (entity classification election), or ask your CPA.",
            },
            {
              key: "industry",
              label: "Industry",
              type: "text",
              placeholder: "e.g., Software consulting",
              description: "Brief description of the business. Used to determine if it may be a Specified Service Trade or Business (SSTB), which limits QBI deduction at higher incomes.",
              source: "Your Schedule C Line B description.",
            },
            {
              key: "naics_code",
              label: "NAICS Code",
              type: "naics",
              description: "6-digit industry code. Helps classify the business type for QBI and other calculations.",
              source: "Schedule C Line B, or look up at census.gov/naics.",
            },
          ],
        },
        {
          label: "Tax Classification Details",
          advanced: true,
          fields: [
            {
              key: "tax_classification",
              label: "Tax Classification",
              type: "select",
              options: [
                { value: "disregarded", label: "Disregarded Entity (Schedule C)" },
                { value: "partnership", label: "Partnership (Form 1065)" },
                { value: "s_corp", label: "S Corporation (Form 1120-S)" },
                { value: "c_corp", label: "C Corporation (Form 1120)" },
              ],
              description: "How the IRS treats the entity for tax purposes. An LLC can elect to be taxed as an S-Corp even if formed as an LLC.",
              source: "Your Form 2553 (S-Corp election) or IRS Form 8832 (entity classification election), or ask your CPA.",
            },
            {
              key: "formation_state",
              label: "Formation State",
              type: "text",
              placeholder: "TX",
              description: "State where the entity was legally formed (Articles of Organization/Incorporation). This is often different from where the business actually operates — a DE LLC that only does business in TX still owes no DE income tax.",
              source: "Your Articles of Organization/Incorporation.",
            },
            {
              key: "operating_states",
              label: "Operating States",
              type: "text",
              placeholder: "TX, CA, NY",
              description: "States where this business earns income, has employees, or maintains a physical presence (tax nexus). Used to evaluate state PTE elections and multi-state tax obligations. The formation state (e.g., DE) is often NOT an operating state. Separate multiple states with commas.",
              source: "States where you file a business or personal state return attributable to this business's activity. Ask your CPA if unsure.",
            },
            {
              key: "qbi_eligible",
              label: "QBI Eligible",
              type: "tristate",
              description: "Whether this business qualifies for the 20% Qualified Business Income deduction (Section 199A). Leave as Unknown to let the scanner evaluate.",
              source: "The scanner evaluates this based on entity type, income, and industry. You can override here.",
            },
            {
              key: "specified_service_trade",
              label: "Specified Service Trade (SSTB)",
              type: "tristate",
              description: "SSTBs (law, health, consulting, financial services, etc.) lose the QBI deduction above the income threshold (~$197k single / $394k MFJ in 2025). Leave Unknown if unsure.",
              source: "IRS Notice 2018-64 lists SSTB categories. Consulting and financial services are SSTBs; engineering and architecture are not.",
            },
          ],
        },
        {
          label: "Financials",
          path: "financials",
          fields: [
            {
              key: "gross_revenue",
              label: "Gross Revenue",
              type: "currency",
              description: "Total revenue before any deductions.",
              source: "Schedule C Line 1, or your P&L statement top line.",
            },
            {
              key: "cost_of_goods_sold",
              label: "Cost of Goods Sold",
              type: "currency",
              description: "Direct costs to produce goods sold. Service businesses typically have $0 here.",
              source: "Schedule C Line 4 or your P&L.",
            },
            {
              key: "operating_expenses",
              label: "Operating Expenses",
              type: "currency",
              description: "All deductible business expenses (advertising, office, supplies, professional fees, etc.).",
              source: "Schedule C Lines 8–27 total, or your P&L expenses section.",
            },
            {
              key: "net_profit_loss",
              label: "Net Profit / (Loss)",
              type: "currency",
              description: "Bottom-line profit after all expenses. This is the amount subject to SE tax and QBI.",
              source: "Schedule C Line 31.",
              calculate: "Gross revenue − COGS − operating expenses = net profit.",
            },
            {
              key: "assets_total",
              label: "Total Assets",
              type: "currency",
              description: "Total business assets (equipment, vehicles, accounts receivable, cash). Required for S-Corp and partnership returns.",
              source: "Your balance sheet or Form 1120-S / 1065 Schedule L.",
            },
            {
              key: "liabilities_total",
              label: "Total Liabilities",
              type: "currency",
              description: "Total business liabilities.",
              source: "Your balance sheet.",
            },
          ],
        },
        {
          label: "Employees",
          path: "employees",
          fields: [
            {
              key: "w2_employees_count",
              label: "W-2 Employees (excl. owner)",
              type: "number",
              description: "Number of W-2 employees other than yourself. The QBI W-2 wage test requires paying W-2 wages.",
              source: "Your payroll records or Form W-3 total.",
            },
            {
              key: "w2_wages_total",
              label: "Total W-2 Wages Paid",
              type: "currency",
              description: "Total wages paid to all W-2 employees (excluding owner W-2 salary). Used in the QBI W-2 wage limitation calculation.",
              source: "Form W-3 Box 1 total, or payroll summary.",
            },
            {
              key: "owner_w2_salary",
              label: "Owner W-2 Salary (S-Corp)",
              type: "currency",
              description: "If you are an S-Corp shareholder-employee, your W-2 salary. IRS requires 'reasonable compensation.' Reduces the net profit flowing to Schedule E.",
              source: "Your S-Corp W-2. Should reflect a reasonable salary for the work performed.",
            },
            {
              key: "independent_contractors",
              label: "Uses Independent Contractors",
              type: "boolean",
              description: "Whether you pay independent contractors. 1099-NEC filing is required for payments ≥ $600.",
              source: "Your payment records to non-employees.",
            },
          ],
        },
        {
          label: "Home Office",
          path: "home_office",
          fields: [
            {
              key: "claimed",
              label: "Home Office Claimed",
              type: "boolean",
              description: "Whether you use part of your home regularly and exclusively for business. Allows deduction of a portion of home expenses.",
              source: "Must be your principal place of business or where you meet clients.",
            },
            {
              key: "method",
              label: "Method",
              type: "select",
              options: [
                { value: "simplified", label: "Simplified ($5/sq ft, max 300 sq ft)" },
                { value: "regular", label: "Regular (actual expenses × business %)" },
              ],
              description: "The simplified method caps at $1,500/year but requires no depreciation tracking. The regular method often produces a larger deduction.",
              source: "Compare both methods; choose the one that gives a larger deduction.",
            },
            {
              key: "square_footage",
              label: "Office Sq Footage",
              type: "number",
              description: "Square footage of the dedicated office space.",
              source: "Measure the room or space used exclusively for business.",
            },
            {
              key: "home_total_sqft",
              label: "Total Home Sq Footage",
              type: "number",
              description: "Total square footage of your home. Used to calculate the business-use percentage for the regular method.",
              source: "Your mortgage appraisal, building permit, or measure the total living area.",
            },
          ],
        },
        {
          label: "Vehicle",
          path: "vehicle",
          fields: [
            {
              key: "business_vehicle",
              label: "Business Vehicle Used",
              type: "boolean",
              description: "Whether you use a vehicle for business purposes. Personal commuting miles are not deductible.",
              source: "Do you drive to client sites, job sites, or other business locations?",
            },
            {
              key: "business_miles",
              label: "Business Miles",
              type: "number",
              description: "Miles driven for business purposes (not commuting). The 2025 standard mileage rate is 70 cents/mile.",
              source: "Your mileage log. Keep a contemporaneous log with date, destination, and business purpose.",
            },
            {
              key: "total_miles",
              label: "Total Miles Driven",
              type: "number",
              description: "Total miles on the vehicle for the year. Used to calculate the business-use percentage for the actual expense method.",
              source: "Your odometer on January 1 vs. December 31.",
            },
            {
              key: "standard_mileage_method",
              label: "Using Standard Mileage",
              type: "boolean",
              description: "Whether you use the IRS standard mileage rate (70¢/mile for 2025). Cannot switch from actual expenses to standard mileage after the first year of vehicle use.",
              source: "Your choice. Standard mileage is simpler; actual expenses may be larger for expensive vehicles.",
            },
          ],
        },
        {
          label: "Retirement Plans",
          path: "retirement_plans",
          advanced: true,
          fields: [
            {
              key: "sep_ira",
              label: "SEP-IRA Established",
              type: "boolean",
              description: "A SEP-IRA allows contributions of up to 25% of net self-employment income (max $70,000 for 2025). Simple to open.",
              source: "Your SEP-IRA account exists at a broker or bank.",
            },
            {
              key: "solo_401k",
              label: "Solo 401(k) Established",
              type: "boolean",
              description: "A Solo 401(k) allows the highest contributions ($23,500 employee + up to 25% employer match in 2025, total max $70,000). Must be opened by December 31.",
              source: "Your Solo 401(k) plan document from your broker.",
            },
            {
              key: "simple_ira",
              label: "SIMPLE IRA Established",
              type: "boolean",
              description: "A SIMPLE IRA is suited for businesses with employees. Employee contribution limit is $16,500 in 2025.",
              source: "Your SIMPLE IRA plan document.",
            },
            {
              key: "defined_benefit",
              label: "Defined Benefit Plan",
              type: "boolean",
              description: "A defined benefit pension plan can allow very large contributions for older, high-income self-employed taxpayers. Requires an actuary.",
              source: "Your plan document from a third-party administrator.",
            },
          ],
        },
        {
          label: "Notes",
          fields: [
            {
              key: "notes",
              label: "Notes",
              type: "textarea",
              placeholder: "Business notes…",
              description: "Notes about this business, pending elections, or planned changes.",
              source: "Your own notes.",
            },
          ],
        },
      ],
    },
  ],
};
