export const schema = {
  label: "Goals & Planning",
  description: "Your tax planning goals, timeline, risk tolerance, and major life events. The scanner uses these to prioritize recommendations.",
  groups: [
    {
      label: "Primary Goals",
      path: "primary_goals",
      fields: [
        {
          key: "reduce_current_year_tax",
          label: "Reduce Current Year Tax",
          type: "boolean",
          description: "Maximize deductions, credits, and deferrals to lower this year's tax bill.",
          source: "Your priority for this filing season.",
        },
        {
          key: "reduce_future_year_tax",
          label: "Reduce Future Year Tax",
          type: "boolean",
          description: "Make moves now (Roth conversions, QOZ investments, installment sales) that reduce tax in future years.",
          source: "Your long-term tax planning priority.",
        },
        {
          key: "reduce_lifetime_tax",
          label: "Minimize Lifetime Tax",
          type: "boolean",
          description: "Optimize across all future years — considering estate, inheritance, and bracket management strategies.",
          source: "Whether you are thinking beyond just this year.",
        },
        {
          key: "build_retirement_wealth",
          label: "Build Retirement Wealth",
          type: "boolean",
          description: "Maximize tax-advantaged retirement account contributions (401k, IRA, SEP, Solo 401k).",
          source: "Whether growing your retirement nest egg is a priority.",
        },
        {
          key: "acquire_real_estate",
          label: "Acquire Real Estate",
          type: "boolean",
          description: "Planning to purchase investment or rental property. Unlocks depreciation, mortgage interest, and 1031 exchange planning.",
          source: "Whether you plan to buy real estate in the near future.",
        },
        {
          key: "start_or_grow_business",
          label: "Start or Grow a Business",
          type: "boolean",
          description: "Launching a new business or expanding an existing one. Relevant for entity selection, SE tax reduction, and startup cost deductions.",
          source: "Whether you are planning a new business venture.",
        },
        {
          key: "reduce_self_employment_tax",
          label: "Reduce SE Tax",
          type: "boolean",
          description: "Minimize the 15.3% self-employment tax through S-Corp election or other entity restructuring.",
          source: "A priority if you have significant self-employment income.",
        },
        {
          key: "protect_assets",
          label: "Asset Protection",
          type: "boolean",
          description: "Structuring assets (LLCs, trusts, retirement accounts) to protect from creditors and liabilities.",
          source: "Whether liability protection is a concern.",
        },
        {
          key: "transfer_wealth_to_heirs",
          label: "Transfer Wealth to Heirs",
          type: "boolean",
          description: "Estate planning strategies — gifting, trusts, stepped-up basis planning, and generation-skipping.",
          source: "Whether legacy and estate planning are priorities.",
        },
        {
          key: "fund_education",
          label: "Fund Education",
          type: "boolean",
          description: "Saving for education via 529 plans, Coverdell ESAs, or other tax-advantaged strategies.",
          source: "Whether funding college or other education is a goal.",
        },
        {
          key: "reduce_healthcare_costs",
          label: "Reduce Healthcare Costs",
          type: "boolean",
          description: "Maximize HSA contributions, Premium Tax Credits, and medical expense deductions.",
          source: "Whether healthcare costs are a significant financial concern.",
        },
        {
          key: "improve_documentation",
          label: "Improve Documentation",
          type: "boolean",
          description: "Get better organized — mileage logs, receipt tracking, document storage — to support deductions in case of audit.",
          source: "Whether your records are currently incomplete or disorganized.",
        },
        {
          key: "prepare_for_audit",
          label: "Audit Preparation",
          type: "boolean",
          description: "Ensure all positions are well-documented and defensible. May involve amended returns, penalty abatement, or IRS correspondence management.",
          source: "Whether you have received or are concerned about an IRS notice.",
        },
        {
          key: "simplify_tax_situation",
          label: "Simplify Tax Situation",
          type: "boolean",
          description: "Reduce complexity — fewer entities, consolidated accounts, simpler structures.",
          source: "Whether your current tax situation feels overly complicated.",
        },
      ],
    },
    {
      label: "Planning Timeline",
      path: "timeline",
      fields: [
        {
          key: "short_term_focus",
          label: "Short-Term Focus (This Year)",
          type: "boolean",
          description: "Primarily focused on the current tax year and next 12 months.",
          source: "Your planning horizon.",
        },
        {
          key: "multi_year_planning",
          label: "Multi-Year Planning (2-5 Years)",
          type: "boolean",
          description: "Looking 2-5 years out — retirement transitions, business sales, large capital events.",
          source: "Your planning horizon.",
        },
        {
          key: "long_term_planning",
          label: "Long-Term Planning (5+ Years)",
          type: "boolean",
          description: "Estate planning, retirement income planning, generational wealth transfer.",
          source: "Your planning horizon.",
        },
      ],
    },
    {
      label: "Risk Tolerance",
      path: "risk_tolerance",
      fields: [
        {
          key: "aggressive_legal_strategies",
          label: "Aggressive (Legal) Strategies",
          type: "boolean",
          description: "Willing to pursue complex or uncommon strategies (cost segregation, Puerto Rico Act 60, DSTs, complex entity structures) that require additional documentation.",
          source: "Your appetite for complexity and audit risk.",
        },
        {
          key: "moderate_strategies",
          label: "Moderate Strategies",
          type: "boolean",
          description: "Standard planning techniques: retirement accounts, real estate depreciation, S-Corp elections, QBI deduction.",
          source: "Most taxpayers fall here.",
        },
        {
          key: "conservative_strategies_only",
          label: "Conservative Only",
          type: "boolean",
          description: "Only straightforward, well-established deductions with minimal audit risk.",
          source: "Your preference if you are very risk-averse about IRS scrutiny.",
        },
      ],
    },
    {
      label: "Professional Advisors",
      path: "professional_advisors",
      fields: [
        {
          key: "cpa_on_file",
          label: "CPA on File",
          type: "boolean",
          description: "Whether you work with a CPA or enrolled agent who prepares your taxes.",
          source: "Your tax preparer.",
        },
        {
          key: "tax_attorney",
          label: "Tax Attorney",
          type: "boolean",
          description: "Whether you have a tax attorney for complex issues (audits, entity structuring, estate planning).",
          source: "Your legal counsel.",
        },
        {
          key: "financial_advisor",
          label: "Financial Advisor",
          type: "boolean",
          description: "Whether you work with a financial planner or investment advisor.",
          source: "Your financial planner.",
        },
        {
          key: "estate_attorney",
          label: "Estate Attorney",
          type: "boolean",
          description: "Whether you have an estate planning attorney (wills, trusts, powers of attorney).",
          source: "Your estate planner.",
        },
      ],
    },
    {
      label: "Major Life Events This Year",
      path: "major_life_events_this_year",
      fields: [
        {
          key: "marriage",
          label: "Marriage",
          type: "boolean",
          description: "Got married this year. Changes filing status and may create a 'marriage penalty' or 'marriage bonus' depending on income.",
          source: "Your marriage certificate.",
        },
        {
          key: "divorce",
          label: "Divorce",
          type: "boolean",
          description: "Divorced or legally separated this year. Changes filing status and may affect alimony deductibility.",
          source: "Your divorce decree.",
        },
        {
          key: "new_child",
          label: "New Child",
          type: "boolean",
          description: "Had or adopted a child this year. Unlocks Child Tax Credit, EITC, and Dependent Care Credit.",
          source: "Birth certificate or adoption decree.",
        },
        {
          key: "home_purchase",
          label: "Home Purchase",
          type: "boolean",
          description: "Purchased a primary residence this year. Points paid at closing may be fully deductible.",
          source: "Your closing disclosure.",
        },
        {
          key: "home_sale",
          label: "Home Sale",
          type: "boolean",
          description: "Sold a primary residence or other real estate this year. May trigger capital gains or qualify for §121 exclusion.",
          source: "Your settlement statement.",
        },
        {
          key: "job_change",
          label: "Job Change",
          type: "boolean",
          description: "Changed employers this year. May have multiple W-2s and excess FICA withholding to recover.",
          source: "Your employment records.",
        },
        {
          key: "started_business",
          label: "Started a Business",
          type: "boolean",
          description: "Started a new business this year. Startup costs (up to $5,000) may be immediately deductible.",
          source: "Your business formation date.",
        },
        {
          key: "sold_business",
          label: "Sold a Business",
          type: "boolean",
          description: "Sold a business interest this year. Complex capital gains and installment sale planning may apply.",
          source: "Your sale agreement.",
        },
        {
          key: "inheritance",
          label: "Received Inheritance",
          type: "boolean",
          description: "Received inherited assets this year. Inherited assets generally receive a stepped-up basis to fair market value at the date of death.",
          source: "Estate distribution records.",
        },
        {
          key: "retirement",
          label: "Retired",
          type: "boolean",
          description: "Retired this year. Changes your income mix and may affect Medicare, SS taxability, and RMD obligations.",
          source: "Your retirement date.",
        },
        {
          key: "large_medical_expense",
          label: "Large Medical Expense",
          type: "boolean",
          description: "Incurred significant medical expenses this year that may make itemizing worthwhile.",
          source: "Your medical bills.",
        },
      ],
    },
    {
      label: "Anticipated Changes Next Year",
      path: "anticipated_changes_next_year",
      fields: [
        {
          key: "income_increase",
          label: "Income Increase Expected",
          type: "boolean",
          description: "Expecting significantly higher income next year. Consider accelerating deductions into this year.",
          source: "Your income forecast.",
        },
        {
          key: "income_decrease",
          label: "Income Decrease Expected",
          type: "boolean",
          description: "Expecting lower income next year. Consider deferring income into next year (Roth conversions, asset sales).",
          source: "Your income forecast.",
        },
        {
          key: "business_start",
          label: "New Business Starting",
          type: "boolean",
          description: "Planning to start a new business next year.",
          source: "Your business plans.",
        },
        {
          key: "real_estate_purchase",
          label: "Real Estate Purchase",
          type: "boolean",
          description: "Planning to purchase real estate next year.",
          source: "Your plans.",
        },
        {
          key: "retirement_start",
          label: "Retirement Starting",
          type: "boolean",
          description: "Planning to retire next year. Requires coordinating Social Security, Medicare enrollment, and RMD planning.",
          source: "Your retirement plans.",
        },
        {
          key: "moving_states",
          label: "Moving to a New State",
          type: "boolean",
          description: "Planning to move to a different state. High-income taxpayers moving to no-income-tax states (TX, FL, NV, etc.) need careful domicile planning.",
          source: "Your relocation plans.",
        },
        {
          key: "new_state",
          label: "New State",
          type: "text",
          placeholder: "TX",
          description: "Two-letter state code of the state you are moving to. No-income-tax states include TX, FL, NV, WA, WY, SD, AK.",
          source: "Your planned destination state.",
        },
      ],
    },
    {
      label: "Notes",
      fields: [
        {
          key: "notes",
          label: "Notes",
          type: "textarea",
          placeholder: "Planning priorities and notes…",
          description: "Any additional context about your goals, concerns, or upcoming decisions.",
          source: "Your own notes.",
        },
      ],
    },
  ],
};
