export const schema = {
  label: "Healthcare",
  description: "Health insurance, HSA, FSA, medical expenses, and related tax items. Accurate healthcare data unlocks HSA deductions, medical expense itemization, and self-employed health insurance deductions.",
  groups: [
    {
      label: "Health Insurance",
      path: "insurance",
      fields: [
        {
          key: "coverage_type",
          label: "Coverage Type",
          type: "select",
          options: [
            { value: "employer", label: "Employer-Sponsored" },
            { value: "marketplace", label: "ACA Marketplace (Healthcare.gov)" },
            { value: "self_purchased", label: "Self-Purchased (off-marketplace)" },
            { value: "medicare", label: "Medicare" },
            { value: "medicaid", label: "Medicaid / CHIP" },
            { value: "tricare", label: "TRICARE (Military)" },
            { value: "spouse_plan", label: "Covered by Spouse's Plan" },
            { value: "uninsured", label: "Uninsured" },
          ],
          description: "How you obtain your health insurance. Marketplace coverage may qualify for the Premium Tax Credit.",
          source: "Your insurance card, explanation of benefits, or HR enrollment confirmation.",
        },
        {
          key: "hdhp_enrolled",
          label: "HDHP Enrolled",
          type: "boolean",
          description: "Whether your plan is a High-Deductible Health Plan (HDHP). Required to contribute to an HSA. 2025 HDHP minimums: $1,650 deductible (self) or $3,300 (family).",
          source: "Your plan documents or insurance card often say 'HDHP.' Check your deductible amount against IRS minimums.",
        },
        {
          key: "hdhp_coverage_level",
          label: "HDHP Coverage Level",
          type: "select",
          options: [
            { value: "self", label: "Self-Only" },
            { value: "family", label: "Family" },
          ],
          description: "Self-only vs. family HDHP coverage determines your maximum HSA contribution. 2025 limits: $4,300 (self) or $8,550 (family), plus $1,000 catch-up if age 55+.",
          source: "Your insurance plan documents.",
        },
        {
          key: "premium_paid_after_tax",
          label: "Premiums Paid After-Tax",
          type: "currency",
          description: "Insurance premiums you paid with after-tax dollars (not through pre-tax payroll deduction). If self-employed, these may be deductible above the line. If you itemize, premiums are medical expenses.",
          source: "Your insurance bills or bank statements. Employer payroll deductions are already pre-tax and not counted here.",
        },
      ],
    },
    {
      label: "Health Savings Account (HSA)",
      path: "health_savings_account",
      fields: [
        {
          key: "hsa_eligible",
          label: "HSA Eligible?",
          type: "tristate",
          description: "Whether you are eligible to contribute to an HSA. Requires enrollment in a qualifying HDHP with no other disqualifying coverage.",
          source: "The scanner evaluates this based on your HDHP enrollment. You are ineligible if you are enrolled in Medicare or claimed as a dependent.",
        },
        {
          key: "existing_balance",
          label: "Existing HSA Balance",
          type: "currency",
          description: "Current balance in your HSA. Unused HSA funds roll over indefinitely — HSAs are often called 'stealth IRAs' for this reason.",
          source: "Your HSA account statement (bank, Fidelity, Optum, etc.).",
        },
        {
          key: "contributions_ytd",
          label: "Contributions YTD",
          type: "currency",
          description: "HSA contributions you made directly this year (outside of payroll). Direct HSA contributions are deductible on Schedule 1. Add to payroll contributions (W-2 Box 12, Code W) for total.",
          source: "Your HSA account statements or contribution records.",
        },
        {
          key: "employer_contributions_ytd",
          label: "Employer Contributions YTD",
          type: "currency",
          description: "Contributions your employer made to your HSA. Excluded from your income. Count toward the annual contribution limit.",
          source: "W-2 Box 12, Code W (includes both employee payroll and employer contributions).",
        },
        {
          key: "distributions_this_year",
          label: "Distributions This Year",
          type: "currency",
          description: "Total amount withdrawn from your HSA this year.",
          source: "Form 1099-SA Box 1.",
        },
        {
          key: "distributions_for_qualified_expenses",
          label: "Used for Qualified Expenses",
          type: "currency",
          description: "The portion of distributions used for qualified medical expenses (tax-free). Non-qualified distributions are taxable plus a 20% penalty (10% if age 65+, disabled, or deceased).",
          source: "Your own records. Keep receipts for HSA qualified expense distributions.",
        },
        {
          key: "investment_account_within_hsa",
          label: "HSA Invested?",
          type: "boolean",
          description: "Whether your HSA balance is invested in mutual funds or ETFs rather than sitting in cash. Invested HSAs grow tax-free.",
          source: "Your HSA account interface — many allow investing once the balance exceeds a threshold.",
        },
      ],
    },
    {
      label: "Healthcare FSA",
      path: "flexible_spending_accounts.healthcare_fsa",
      fields: [
        {
          key: "enrolled",
          label: "Healthcare FSA Enrolled",
          type: "boolean",
          description: "Whether you have a healthcare FSA through your employer. 2025 employee contribution limit is $3,300. Cannot have both an FSA and an HSA (unless it's a limited-purpose FSA).",
          source: "Your employer's HR benefits enrollment.",
        },
        {
          key: "election_amount",
          label: "FSA Election Amount",
          type: "currency",
          description: "How much you elected to contribute to the FSA this plan year.",
          source: "Your benefits enrollment confirmation.",
        },
        {
          key: "balance",
          label: "Current FSA Balance",
          type: "currency",
          description: "Current available FSA balance. FSA funds are use-it-or-lose-it unless your plan allows a rollover or grace period.",
          source: "Your FSA administrator portal.",
        },
        {
          key: "rollover_allowed",
          label: "Rollover Allowed?",
          type: "tristate",
          description: "Whether your plan allows rolling over unused funds (up to $660 in 2025) to the next plan year.",
          source: "Your plan documents or HR.",
        },
      ],
    },
    {
      label: "Dependent Care FSA",
      path: "flexible_spending_accounts.dependent_care_fsa",
      fields: [
        {
          key: "enrolled",
          label: "Dependent Care FSA Enrolled",
          type: "boolean",
          description: "Whether you have a dependent care FSA. Up to $5,000 ($2,500 if MFS) can be excluded from income for qualifying child or dependent care expenses.",
          source: "Your employer's HR benefits enrollment.",
        },
        {
          key: "election_amount",
          label: "Election Amount",
          type: "currency",
          description: "Your annual dependent care FSA election.",
          source: "Your benefits enrollment confirmation.",
        },
        {
          key: "qualifying_expenses_ytd",
          label: "Qualifying Expenses YTD",
          type: "currency",
          description: "Eligible care expenses incurred (daycare, after-school, summer day camp for children under 13). Coordinates with the Child and Dependent Care Credit.",
          source: "Your daycare and care provider receipts.",
        },
      ],
    },
    {
      label: "Medical Expenses",
      path: "medical_expenses",
      fields: [
        {
          key: "total_out_of_pocket",
          label: "Total Out-of-Pocket",
          type: "currency",
          description: "All unreimbursed qualified medical, dental, and vision expenses paid. Deductible on Schedule A only to the extent they exceed 7.5% of your AGI.",
          source: "Your explanation of benefits, pharmacy receipts, and medical bills. Exclude insurance premiums paid pre-tax.",
          calculate: "Only the amount above 7.5% × AGI is deductible. Example: AGI $100k → threshold $7,500 → $10,000 expenses → $2,500 deductible.",
        },
        {
          key: "large_medical_events_this_year",
          label: "Major Medical Events",
          type: "boolean",
          description: "Whether you had a major medical event (surgery, hospitalization, serious illness) that generated significant expenses. May make itemizing worthwhile.",
          source: "Your medical bills and insurance explanation of benefits.",
        },
        {
          key: "dental_expenses",
          label: "Dental Expenses",
          type: "currency",
          description: "Unreimbursed dental care costs (cleanings, fillings, orthodontia, etc.). These are qualified medical expenses for Schedule A.",
          source: "Your dental bills and insurance EOBs.",
        },
        {
          key: "vision_expenses",
          label: "Vision Expenses",
          type: "currency",
          description: "Unreimbursed vision care (exams, glasses, contacts, LASIK). Qualify as medical expenses.",
          source: "Your optometrist bills and insurance EOBs.",
        },
        {
          key: "prescription_expenses",
          label: "Prescription Expenses",
          type: "currency",
          description: "Unreimbursed prescription medication costs.",
          source: "Your pharmacy receipts or insurance EOBs.",
        },
      ],
    },
    {
      label: "Self-Employed Health Insurance",
      path: "self_employed_health_insurance",
      fields: [
        {
          key: "owner_health_insurance_premium",
          label: "Owner Health Insurance Premium",
          type: "currency",
          description: "Health, dental, and qualified long-term care insurance premiums for yourself (and family) as a self-employed person. Deductible above the line as an adjustment to income. Cannot exceed your business net profit.",
          source: "Your insurance premium statements or bank records. Must be in your name or the business's name.",
        },
        {
          key: "family_covered",
          label: "Family Covered",
          type: "boolean",
          description: "Whether your policy also covers your spouse and dependents.",
          source: "Your insurance policy documents.",
        },
      ],
    },
    {
      label: "Premium Tax Credit (Marketplace)",
      path: "premium_tax_credit",
      fields: [
        {
          key: "marketplace_coverage",
          label: "Marketplace Coverage",
          type: "boolean",
          description: "Whether you purchased insurance through the ACA Marketplace (Healthcare.gov or a state exchange). Required to claim or reconcile the Premium Tax Credit.",
          source: "Your Healthcare.gov account or Form 1095-A from the marketplace.",
        },
        {
          key: "advance_ptc_received",
          label: "Advance PTC Received",
          type: "boolean",
          description: "Whether you received advance Premium Tax Credit payments to reduce your monthly premiums. Must reconcile on Form 8962 — if income was higher than estimated, you may owe some back.",
          source: "Form 1095-A Column C (advance payments made).",
        },
      ],
    },
    {
      label: "Notes",
      fields: [
        {
          key: "notes",
          label: "Notes",
          type: "textarea",
          placeholder: "Healthcare notes…",
          description: "Notes about your healthcare coverage, medical events, or HSA strategy.",
          source: "Your own notes.",
        },
      ],
    },
  ],
};
