import { ageAsOfYearEnd } from "../lib/dateDerived.js";

const SPOUSE_FILING_STATUSES = ["married_filing_jointly", "married_filing_separately", "qualifying_surviving_spouse"];
const hasSpouse = (data) => SPOUSE_FILING_STATUSES.includes(data?.filing_status);

export const schema = {
  label: "Household & Filing",
  description: "Your filing status, residence, and family situation. These fields affect nearly every calculation in the scanner.",
  groups: [
    {
      label: "Your Info",
      path: "taxpayer",
      fields: [
        {
          key: "first_name",
          label: "First Name",
          type: "text",
          essential: true,
          description: "Your legal first name as it appears on your Social Security card. Printed on Form 1040.",
          source: "Your Social Security card or prior-year tax return.",
        },
        {
          key: "last_name",
          label: "Last Name",
          type: "text",
          essential: true,
          description: "Your legal last name as it appears on your Social Security card. Printed on Form 1040.",
          source: "Your Social Security card or prior-year tax return.",
        },
        {
          key: "ssn",
          label: "Social Security Number",
          type: "ssn",
          description: "Your SSN is required on Form 1040 and all schedules. Stored locally only — never transmitted to third parties.",
          source: "Your Social Security card.",
        },
        {
          key: "dob",
          label: "Date of Birth",
          type: "date",
          description: "Your date of birth. Used to determine if you were born before January 2, 1961 (additional standard deduction) and for IRA/RMD age calculations.",
          source: "Your birth certificate or driver's license.",
        },
        {
          key: "age",
          label: "Age",
          type: "number",
          derivedFrom: (groupData, sectionData) => ageAsOfYearEnd(groupData?.dob, sectionData),
          description: "Your age as of December 31 of the tax year. Auto-calculated from Date of Birth. Determines catch-up contribution eligibility (age 50+), IRA deductibility, Medicare, and senior additional standard deduction (age 65+).",
          source: "Calculated automatically from your Date of Birth.",
        },
      ],
    },
    {
      label: "Filing Status",
      fields: [
        {
          key: "filing_status",
          label: "Filing Status",
          type: "select",
          essential: true,
          options: [
            { value: "single", label: "Single" },
            { value: "married_filing_jointly", label: "Married Filing Jointly" },
            { value: "married_filing_separately", label: "Married Filing Separately" },
            { value: "head_of_household", label: "Head of Household" },
            { value: "qualifying_surviving_spouse", label: "Qualifying Surviving Spouse" },
          ],
          description: "Your IRS filing category for the return. Determines your standard deduction, tax brackets, and eligibility phase-out thresholds.",
          source: "Check last year's Form 1040, Line 1 (the five checkboxes at the top). Or ask your CPA what status you filed.",
        },
        {
          key: "tax_year",
          label: "Tax Year",
          type: "number",
          placeholder: "2025",
          description: "The calendar year this return covers.",
          source: "Use the current year if you are planning ahead, or last year if you are preparing a return.",
        },
        {
          key: "estimated_agi",
          label: "Estimated AGI",
          type: "currency",
          description: "Your approximate Adjusted Gross Income — total income minus above-the-line deductions, before the standard or itemized deduction.",
          source: "Last year's Form 1040 Line 11. Use that as a baseline and adjust for expected changes.",
          calculate: "Add W-2 Box 1 wages + Schedule C net profit + 1099-DIV/INT totals + rental net income, then subtract student loan interest, HSA deductions, and self-employed health insurance premiums.",
        },
        {
          key: "prior_year_agi",
          label: "Prior Year AGI",
          type: "currency",
          description: "Your AGI from the last completed filed return. Used for safe-harbor estimated tax calculations.",
          source: "Form 1040 Line 11 from the return you filed last year.",
        },
        {
          key: "estimated_net_worth",
          label: "Estimated Net Worth",
          type: "currency",
          description: "Rough total of everything you own minus everything you owe. Only used to flag estate-scale planning (the estate/GST exemption is $13.99M per person in 2025).",
          source: "Add up accounts, real estate, and business value; subtract mortgages and other debts. A rough estimate is fine.",
        },
        {
          key: "itemizing_deductions",
          label: "Itemizing Deductions?",
          type: "tristate",
          description: "Whether you expect to itemize (Schedule A) instead of taking the standard deduction. Affects mortgage interest, charitable, and state tax deduction opportunities.",
          source: "You itemize when your Schedule A total (mortgage interest + property tax + charity + medical) exceeds your standard deduction. The scanner will flag if itemizing looks beneficial.",
        },
        {
          key: "digital_assets",
          label: "Digital Assets (Yes/No)",
          type: "boolean",
          description: "Answer 'Yes' if at any time during the tax year you received, sold, exchanged, or otherwise disposed of a digital asset (cryptocurrency, NFT, etc.). This is a required checkbox on Form 1040.",
          source: "Form 1040 Digital Assets question. Required regardless of whether you had a gain or loss.",
        },
      ],
    },
    {
      label: "Address",
      path: "residence",
      fields: [
        {
          key: "street_address",
          label: "Street Address",
          type: "text",
          placeholder: "123 Main St",
          description: "Your home address (number and street). Printed on Form 1040.",
          source: "Your mailing address.",
        },
        {
          key: "apt_number",
          label: "Apt. / Unit No.",
          type: "text",
          placeholder: "Apt 4B",
          description: "Apartment, unit, suite, or room number. Leave blank if not applicable.",
          source: "Your mailing address.",
        },
        {
          key: "city",
          label: "City",
          type: "text",
          description: "City of residence. Some cities levy local income taxes.",
          source: "Your mailing address city.",
        },
        {
          key: "state",
          label: "State",
          type: "text",
          placeholder: "TX",
          essential: true,
          description: "Two-letter state abbreviation where you are domiciled for tax purposes. Affects state income tax and some federal deduction calculations.",
          source: "The state on your driver's license or the state where you maintain your permanent home.",
        },
        {
          key: "zip",
          label: "ZIP Code",
          type: "zip",
          placeholder: "78701",
          description: "Five-digit ZIP code. Used to identify local tax jurisdictions.",
          source: "Your mailing address.",
        },
        {
          key: "county",
          label: "County",
          type: "text",
          description: "County of residence. Used for certain local tax and property tax calculations.",
          source: "Your property tax bill or county government website.",
        },
      ],
    },
    {
      label: "Spouse",
      path: "spouse",
      showIf: hasSpouse,
      fields: [
        {
          key: "present",
          label: "Spouse Present",
          type: "boolean",
          description: "Whether you have a spouse for filing purposes (married as of December 31).",
          source: "Marital status on December 31 of the tax year.",
        },
        {
          key: "first_name",
          label: "Spouse First Name",
          type: "text",
          description: "Spouse's legal first name as on their Social Security card. Required on a joint return.",
          source: "Spouse's Social Security card or prior-year tax return.",
        },
        {
          key: "last_name",
          label: "Spouse Last Name",
          type: "text",
          description: "Spouse's legal last name. Required on a joint return.",
          source: "Spouse's Social Security card or prior-year tax return.",
        },
        {
          key: "ssn",
          label: "Spouse SSN",
          type: "ssn",
          description: "Spouse's Social Security Number. Required on Form 1040 for joint and MFS returns. Stored locally only.",
          source: "Spouse's Social Security card.",
        },
        {
          key: "dob",
          label: "Spouse Date of Birth",
          type: "date",
          description: "Spouse's date of birth. Used for the born-before-Jan-2-1961 additional standard deduction check.",
          source: "Spouse's birth certificate or driver's license.",
        },
        {
          key: "age",
          label: "Spouse Age",
          type: "number",
          derivedFrom: (groupData, sectionData) => ageAsOfYearEnd(groupData?.dob, sectionData),
          description: "Spouse's age as of December 31. Auto-calculated from Spouse Date of Birth. Determines catch-up contributions and senior standard deduction.",
          source: "Calculated automatically from Spouse Date of Birth.",
        },
        {
          key: "employed",
          label: "Spouse W-2 Employed",
          type: "tristate",
          description: "Whether your spouse has W-2 wages from an employer. Affects dual-income phase-outs and employer retirement plan access.",
          source: "Does your spouse receive a W-2 from an employer?",
        },
        {
          key: "self_employed",
          label: "Spouse Self-Employed",
          type: "tristate",
          description: "Whether your spouse has self-employment income. Affects SE tax deduction and self-employed health insurance deduction eligibility.",
          source: "Does your spouse have business income reported on Schedule C or a K-1?",
        },
      ],
    },
    {
      label: "Dependents",
      type: "callout",
      goToSection: "dependents",
      actionLabel: "Manage Dependents →",
      text: (cross) => {
        const n = cross?.dependentsCount;
        if (n == null) return "Dependents count available after opening the Dependents section.";
        return n === 1 ? "1 dependent on file." : `${n} dependents on file.`;
      },
    },
    {
      label: "Payments & Direct Deposit",
      path: "payments",
      fields: [
        {
          key: "estimated_tax_payments",
          label: "Estimated Tax Payments",
          type: "currency",
          description: "Total federal estimated tax payments made during the year (Form 1040-ES). Also include any overpayment applied from your prior-year return.",
          source: "Your 1040-ES payment receipts, IRS account transcript, or bank records. Sum all four quarterly payments.",
        },
        {
          key: "other_withholding",
          label: "Other Federal Withholding",
          type: "currency",
          description: "Federal income tax withheld from sources other than W-2s — for example, backup withholding on 1099-INT/DIV/B, withholding on IRA distributions (Form 1099-R Box 4), or other federal withholding.",
          source: "Form 1099-R Box 4 (IRA/pension withholding), Form 1099-INT/DIV Box 4 (backup withholding). Sum all non-W-2 federal withholding shown on your 1099s.",
        },
        {
          key: "earned_income_credit",
          label: "Earned Income Credit (EIC)",
          type: "currency",
          description: "Earned Income Tax Credit — a refundable credit for low-to-moderate income workers. Use the IRS EIC table in the Form 1040 instructions or the IRS online EITC assistant to look up your amount based on earned income, filing status, and number of qualifying children. Goes on Form 1040 Line 27.",
          source: "Form 1040 Line 27. The credit ranges from $649 (no children) to $8,046 (3+ children) for 2025. Phase-out applies at higher incomes. Use the IRS EITC assistant at irs.gov/eitc for your exact amount.",
          calculate: "Based on the lower of earned income or AGI, filing status, and number of qualifying children. Investment income must be under $11,950 to qualify.",
        },
        {
          key: "apply_to_next_year",
          label: "Apply Overpayment to Next Year",
          type: "currency",
          description: "If you are getting a refund, enter how much of the overpayment you want applied to next year's estimated taxes instead of refunded. Leave blank to receive the full refund.",
          source: "Form 1040 Line 36. Your decision — enter $0 to get the full refund now.",
        },
        {
          key: "routing_number",
          label: "Bank Routing Number",
          type: "routing",
          description: "Your bank's 9-digit ABA routing number for direct deposit of your refund. The routing number is the first 9 digits at the bottom-left of a check.",
          source: "Form 1040 Line 35b. Your check or online banking account details.",
        },
        {
          key: "account_number",
          label: "Bank Account Number",
          type: "text",
          description: "Your bank account number for direct deposit. Found at the bottom of a check after the routing number.",
          source: "Form 1040 Line 35d. Your check or online banking account details.",
        },
        {
          key: "account_type",
          label: "Account Type",
          type: "select",
          options: [
            { value: "checking", label: "Checking" },
            { value: "savings", label: "Savings" },
          ],
          description: "Whether the account is a checking or savings account. The IRS uses this to route the direct deposit correctly.",
          source: "Form 1040 Line 35c. Match the type of account you entered above.",
        },
      ],
    },
    {
      label: "Filing Edge Cases",
      advanced: true,
      fields: [
        {
          key: "presidential_campaign_you",
          label: "Presidential Election Campaign — You",
          type: "boolean",
          description: "Check to direct $3 of your taxes to the Presidential Election Campaign Fund. Does not change your tax or refund. Optional.",
          source: "Form 1040 top-right checkbox labeled 'You'.",
        },
        {
          key: "presidential_campaign_spouse",
          label: "Presidential Election Campaign — Spouse",
          type: "boolean",
          description: "If filing jointly, check to direct $3 of your spouse's taxes to the Presidential Election Campaign Fund. Optional.",
          source: "Form 1040 top-right checkbox labeled 'Spouse'.",
        },
        {
          key: "hoh_qualifying_person_name",
          label: "HOH Qualifying Person Name",
          type: "text",
          description: "If filing Head of Household and the qualifying person is your child but NOT your dependent (e.g., a child who can be claimed by the other parent), enter their name here.",
          source: "Form 1040 filing status section, HOH qualifier name line.",
        },
        {
          key: "section_9100_2",
          label: "Filed Pursuant to Section 301.9100-2",
          type: "boolean",
          description: "Check if this return is filed pursuant to section 301.9100-2 to make a late election. Used when amending a return within 6 months of the original due date to make an election not timely made.",
          source: "Form 1040 top header checkbox. Your tax advisor will tell you if this applies.",
        },
        {
          key: "combat_zone",
          label: "Combat Zone",
          type: "boolean",
          description: "Check if you served in a designated combat zone during the tax year. Combat zone service may extend filing deadlines and exclude certain pay from income.",
          source: "Form 1040 top header checkbox. See IRS Publication 3 (Armed Forces' Tax Guide).",
        },
        {
          key: "taxpayer_deceased",
          label: "Taxpayer Deceased",
          type: "boolean",
          description: "Check if the taxpayer died during the tax year. The personal representative or surviving spouse files the return.",
          source: "Form 1040 top header. Required if filing on behalf of a deceased taxpayer.",
        },
        {
          key: "taxpayer_date_of_death",
          label: "Taxpayer Date of Death",
          type: "date",
          description: "Date the taxpayer died, if applicable. Printed in the Form 1040 header.",
          source: "Death certificate.",
        },
        {
          key: "spouse_deceased",
          label: "Spouse Deceased",
          type: "boolean",
          description: "Check if the spouse died during the tax year on a joint return.",
          source: "Form 1040 top header.",
        },
        {
          key: "spouse_date_of_death",
          label: "Spouse Date of Death",
          type: "date",
          description: "Date the spouse died, if applicable. Printed in the Form 1040 header.",
          source: "Death certificate.",
        },
      ],
    },
    {
      label: "Foreign Address",
      path: "residence",
      advanced: true,
      fields: [
        {
          key: "foreign_country",
          label: "Foreign Country Name",
          type: "text",
          description: "If your mailing address is outside the U.S., enter the country name. Leave blank for U.S. addresses.",
          source: "Form 1040 address section — foreign country line.",
        },
        {
          key: "foreign_province",
          label: "Foreign Province / State / County",
          type: "text",
          description: "Province, state, or county for a foreign mailing address.",
          source: "Form 1040 address section — foreign province/state/county line.",
        },
        {
          key: "foreign_postal_code",
          label: "Foreign Postal Code",
          type: "text",
          description: "Postal code for a foreign mailing address.",
          source: "Form 1040 address section — foreign postal code line.",
        },
      ],
    },
    {
      label: "Your Situation",
      path: "taxpayer",
      advanced: true,
      fields: [
        {
          key: "blind",
          label: "Legally Blind",
          type: "boolean",
          description: "Whether you are legally blind per IRS definition (visual acuity 20/200 or less in the better eye with glasses, or field of vision 20 degrees or less). Grants an additional standard deduction.",
          source: "Your eye doctor can provide documentation. The IRS additional amount for 2025 is $1,850 (single) or $1,500 (married).",
        },
        {
          key: "disabled",
          label: "Disabled",
          type: "boolean",
          description: "Whether you are disabled per IRS or SSA definition. Affects EITC eligibility, early distribution penalty exceptions, and certain credits.",
          source: "SSA disability determination letter, or a statement from a licensed physician.",
        },
        {
          key: "active_military",
          label: "Active Military",
          type: "boolean",
          description: "Whether you are on active duty military service. Unlocks combat pay exclusions, moving expense deductions, and SCRA protections.",
          source: "Your military orders or Leave and Earnings Statement (LES).",
        },
        {
          key: "veteran",
          label: "Veteran",
          type: "boolean",
          description: "Whether you are a military veteran. Relevant for certain state tax exemptions and VA benefit exclusions.",
          source: "Your DD-214 discharge papers.",
        },
        {
          key: "student",
          label: "Full-Time Student",
          type: "boolean",
          description: "Whether you are a full-time student. Affects EITC eligibility rules for taxpayers under age 25 and dependency status.",
          source: "Full-time enrollment status from your school.",
        },
        {
          key: "can_be_claimed_as_dependent",
          label: "Can Be Claimed as Dependent",
          type: "boolean",
          description: "Check if someone else (e.g., a parent) can claim you as a dependent on their return. If yes, your standard deduction is limited to the greater of $1,350 or earned income + $450 (2025), not the full $15,750.",
          source: "Form 1040 Page 2, Line 12a checkbox 'Someone can claim: You as a dependent'.",
        },
        {
          key: "dual_status_alien",
          label: "Dual-Status Alien",
          type: "boolean",
          description: "Check if you were a dual-status alien (part-year resident and part-year nonresident) during the tax year. Affects standard deduction eligibility.",
          source: "Form 1040 Page 2, Line 12c. See IRS Publication 519 for dual-status filing rules.",
        },
      ],
    },
    {
      label: "Spouse Situation",
      path: "spouse",
      advanced: true,
      showIf: hasSpouse,
      fields: [
        {
          key: "can_be_claimed_as_dependent",
          label: "Spouse Can Be Claimed as Dependent",
          type: "boolean",
          description: "Check if someone else can claim your spouse as a dependent. Rare, but affects the standard deduction on a joint return.",
          source: "Form 1040 Page 2, Line 12a checkbox 'Your spouse as a dependent'.",
        },
        {
          key: "itemizes_separately",
          label: "Spouse Itemizes on Separate Return",
          type: "boolean",
          description: "If filing Married Filing Separately and your spouse itemizes deductions on their separate return, you cannot take the standard deduction — you must also itemize.",
          source: "Form 1040 Page 2, Line 12b. Check if your spouse is itemizing on their MFS return.",
        },
      ],
    },
    {
      label: "Joint Payments with Former Spouse",
      path: "payments",
      advanced: true,
      fields: [
        {
          key: "former_spouse_ssn",
          label: "Former Spouse SSN",
          type: "ssn",
          description: "If you made 2025 estimated tax payments jointly with a former spouse and are now filing separately, enter their Social Security Number so the IRS can allocate the payments correctly.",
          source: "Form 1040 Line 26 footnote field. Only required if estimated payments were made jointly with a former spouse on a joint 2024 return and you are now filing separately.",
        },
      ],
    },
    {
      label: "Notes",
      fields: [
        {
          key: "notes",
          label: "Notes",
          type: "textarea",
          placeholder: "Household planning notes…",
          description: "Free-form notes about your household situation that don't fit the structured fields.",
          source: "Your own notes.",
        },
      ],
    },
  ],
};
