export const schema = {
  label: "Household & Filing",
  description: "Your filing status, residence, and family situation. These fields affect nearly every calculation in the scanner.",
  groups: [
    {
      label: "Filing Basics",
      fields: [
        {
          key: "filing_status",
          label: "Filing Status",
          type: "select",
          options: [
            { value: "single", label: "Single" },
            { value: "married_filing_jointly", label: "Married Filing Jointly" },
            { value: "married_filing_separately", label: "Married Filing Separately" },
            { value: "head_of_household", label: "Head of Household" },
            { value: "qualifying_surviving_spouse", label: "Qualifying Surviving Spouse" },
          ],
          description: "Your IRS filing category for the return. Determines your standard deduction, tax brackets, and eligibility phase-out thresholds.",
          source: "Check last year's Form 1040, Line 1 (the five checkboxes at the top). Or ask your CPA what status you filed.",
        },
        {
          key: "tax_year",
          label: "Tax Year",
          type: "number",
          placeholder: "2025",
          description: "The calendar year this return covers.",
          source: "Use the current year if you are planning ahead, or last year if you are preparing a return.",
        },
        {
          key: "estimated_agi",
          label: "Estimated AGI",
          type: "currency",
          description: "Your approximate Adjusted Gross Income — total income minus above-the-line deductions, before the standard or itemized deduction.",
          source: "Last year's Form 1040 Line 11. Use that as a baseline and adjust for expected changes.",
          calculate: "Add W-2 Box 1 wages + Schedule C net profit + 1099-DIV/INT totals + rental net income, then subtract student loan interest, HSA deductions, and self-employed health insurance premiums.",
        },
        {
          key: "prior_year_agi",
          label: "Prior Year AGI",
          type: "currency",
          description: "Your AGI from the last completed filed return. Used for safe-harbor estimated tax calculations.",
          source: "Form 1040 Line 11 from the return you filed last year.",
        },
        {
          key: "itemizing_deductions",
          label: "Itemizing Deductions?",
          type: "tristate",
          description: "Whether you expect to itemize (Schedule A) instead of taking the standard deduction. Affects mortgage interest, charitable, and state tax deduction opportunities.",
          source: "You itemize when your Schedule A total (mortgage interest + property tax + charity + medical) exceeds your standard deduction. The scanner will flag if itemizing looks beneficial.",
        },
        {
          key: "digital_assets",
          label: "Digital Assets (Yes/No)",
          type: "boolean",
          description: "Answer 'Yes' if at any time during the tax year you received, sold, exchanged, or otherwise disposed of a digital asset (cryptocurrency, NFT, etc.). This is a required checkbox on Form 1040.",
          source: "Form 1040 Digital Assets question. Required regardless of whether you had a gain or loss.",
        },
      ],
    },
    {
      label: "Residence",
      path: "residence",
      fields: [
        {
          key: "street_address",
          label: "Street Address",
          type: "text",
          placeholder: "123 Main St",
          description: "Your home address (number and street). Printed on Form 1040.",
          source: "Your mailing address.",
        },
        {
          key: "apt_number",
          label: "Apt. / Unit No.",
          type: "text",
          placeholder: "Apt 4B",
          description: "Apartment, unit, suite, or room number. Leave blank if not applicable.",
          source: "Your mailing address.",
        },
        {
          key: "city",
          label: "City",
          type: "text",
          description: "City of residence. Some cities levy local income taxes.",
          source: "Your mailing address city.",
        },
        {
          key: "state",
          label: "State",
          type: "text",
          placeholder: "TX",
          description: "Two-letter state abbreviation where you are domiciled for tax purposes. Affects state income tax and some federal deduction calculations.",
          source: "The state on your driver's license or the state where you maintain your permanent home.",
        },
        {
          key: "zip",
          label: "ZIP Code",
          type: "text",
          placeholder: "78701",
          description: "Five-digit ZIP code. Used to identify local tax jurisdictions.",
          source: "Your mailing address.",
        },
        {
          key: "county",
          label: "County",
          type: "text",
          description: "County of residence. Used for certain local tax and property tax calculations.",
          source: "Your property tax bill or county government website.",
        },
      ],
    },
    {
      label: "Taxpayer",
      path: "taxpayer",
      fields: [
        {
          key: "first_name",
          label: "First Name",
          type: "text",
          description: "Your legal first name as it appears on your Social Security card. Printed on Form 1040.",
          source: "Your Social Security card or prior-year tax return.",
        },
        {
          key: "last_name",
          label: "Last Name",
          type: "text",
          description: "Your legal last name as it appears on your Social Security card. Printed on Form 1040.",
          source: "Your Social Security card or prior-year tax return.",
        },
        {
          key: "ssn",
          label: "Social Security Number",
          type: "text",
          placeholder: "XXX-XX-XXXX",
          description: "Your SSN is required on Form 1040 and all schedules. Stored locally only — never transmitted to third parties.",
          source: "Your Social Security card.",
        },
        {
          key: "dob",
          label: "Date of Birth",
          type: "date",
          description: "Your date of birth. Used to determine if you were born before January 2, 1961 (additional standard deduction) and for IRA/RMD age calculations.",
          source: "Your birth certificate or driver's license.",
        },
        {
          key: "age",
          label: "Age",
          type: "number",
          description: "Your age as of December 31 of the tax year. Determines catch-up contribution eligibility (age 50+), IRA deductibility, Medicare, and senior additional standard deduction (age 65+).",
          source: "Your date of birth. The age that matters is your age on December 31 of the tax year.",
        },
        {
          key: "blind",
          label: "Legally Blind",
          type: "boolean",
          description: "Whether you are legally blind per IRS definition (visual acuity 20/200 or less in the better eye with glasses, or field of vision 20 degrees or less). Grants an additional standard deduction.",
          source: "Your eye doctor can provide documentation. The IRS additional amount for 2025 is $1,850 (single) or $1,500 (married).",
        },
        {
          key: "disabled",
          label: "Disabled",
          type: "boolean",
          description: "Whether you are disabled per IRS or SSA definition. Affects EITC eligibility, early distribution penalty exceptions, and certain credits.",
          source: "SSA disability determination letter, or a statement from a licensed physician.",
        },
        {
          key: "active_military",
          label: "Active Military",
          type: "boolean",
          description: "Whether you are on active duty military service. Unlocks combat pay exclusions, moving expense deductions, and SCRA protections.",
          source: "Your military orders or Leave and Earnings Statement (LES).",
        },
        {
          key: "veteran",
          label: "Veteran",
          type: "boolean",
          description: "Whether you are a military veteran. Relevant for certain state tax exemptions and VA benefit exclusions.",
          source: "Your DD-214 discharge papers.",
        },
        {
          key: "student",
          label: "Full-Time Student",
          type: "boolean",
          description: "Whether you are a full-time student. Affects EITC eligibility rules for taxpayers under age 25 and dependency status.",
          source: "Full-time enrollment status from your school.",
        },
      ],
    },
    {
      label: "Spouse",
      path: "spouse",
      fields: [
        {
          key: "present",
          label: "Spouse Present",
          type: "boolean",
          description: "Whether you have a spouse for filing purposes (married as of December 31).",
          source: "Marital status on December 31 of the tax year.",
        },
        {
          key: "first_name",
          label: "Spouse First Name",
          type: "text",
          description: "Spouse's legal first name as on their Social Security card. Required on a joint return.",
          source: "Spouse's Social Security card or prior-year tax return.",
        },
        {
          key: "last_name",
          label: "Spouse Last Name",
          type: "text",
          description: "Spouse's legal last name. Required on a joint return.",
          source: "Spouse's Social Security card or prior-year tax return.",
        },
        {
          key: "ssn",
          label: "Spouse SSN",
          type: "text",
          placeholder: "XXX-XX-XXXX",
          description: "Spouse's Social Security Number. Required on Form 1040 for joint and MFS returns. Stored locally only.",
          source: "Spouse's Social Security card.",
        },
        {
          key: "dob",
          label: "Spouse Date of Birth",
          type: "date",
          description: "Spouse's date of birth. Used for the born-before-Jan-2-1961 additional standard deduction check.",
          source: "Spouse's birth certificate or driver's license.",
        },
        {
          key: "age",
          label: "Spouse Age",
          type: "number",
          description: "Spouse's age as of December 31. Determines catch-up contributions and senior standard deduction.",
          source: "Spouse's date of birth, age on December 31.",
        },
        {
          key: "employed",
          label: "Spouse W-2 Employed",
          type: "tristate",
          description: "Whether your spouse has W-2 wages from an employer. Affects dual-income phase-outs and employer retirement plan access.",
          source: "Does your spouse receive a W-2 from an employer?",
        },
        {
          key: "self_employed",
          label: "Spouse Self-Employed",
          type: "tristate",
          description: "Whether your spouse has self-employment income. Affects SE tax deduction and self-employed health insurance deduction eligibility.",
          source: "Does your spouse have business income reported on Schedule C or a K-1?",
        },
      ],
    },
    {
      label: "Dependents",
      path: "dependents",
      fields: [
        {
          key: "count",
          label: "Dependent Count",
          type: "number",
          placeholder: "0",
          description: "Total number of qualifying dependents you can claim. Affects Child Tax Credit, EITC, Head of Household status, and Dependent Care Credit.",
          source: "Count children and other qualifying relatives you can claim. See the Dependents section for detail on each person.",
        },
      ],
    },
    {
      label: "Payments & Withholding",
      path: "payments",
      fields: [
        {
          key: "estimated_tax_payments",
          label: "Estimated Tax Payments",
          type: "currency",
          description: "Total federal estimated tax payments made during the year (Form 1040-ES). Also include any overpayment applied from your prior-year return.",
          source: "Your 1040-ES payment receipts, IRS account transcript, or bank records. Sum all four quarterly payments.",
        },
        {
          key: "other_withholding",
          label: "Other Federal Withholding",
          type: "currency",
          description: "Federal income tax withheld from sources other than W-2s — for example, backup withholding on 1099-INT/DIV/B, withholding on IRA distributions (Form 1099-R Box 4), or other federal withholding.",
          source: "Form 1099-R Box 4 (IRA/pension withholding), Form 1099-INT/DIV Box 4 (backup withholding). Sum all non-W-2 federal withholding shown on your 1099s.",
        },
      ],
    },
    {
      label: "Notes",
      fields: [
        {
          key: "notes",
          label: "Notes",
          type: "textarea",
          placeholder: "Household planning notes…",
          description: "Free-form notes about your household situation that don't fit the structured fields.",
          source: "Your own notes.",
        },
      ],
    },
  ],
};
