export const schema = {
  label: "Income",
  description: "All income sources and above-the-line adjustments. Accurate income data is the foundation of every opportunity calculation.",
  groups: [
    {
      label: "W-2 Employment",
      type: "list",
      key: "w2_employment",
      addLabel: "Add W-2 Employer",
      itemLabel: "W-2 Job",
      description: "Each employer from which you received a W-2 this year.",
      source: "Your W-2 forms. Employers must mail W-2s by January 31.",
      itemGroups: [
        {
          label: "W-2 Details",
          fields: [
            {
              key: "employer_name",
              label: "Employer Name",
              type: "text",
              description: "The company name on the W-2.",
              source: "W-2 Box c (Employer's name).",
            },
            {
              key: "wages",
              label: "Wages (Box 1)",
              type: "currency",
              description: "Taxable wages, tips, and other compensation from this employer.",
              source: "W-2 Box 1.",
            },
            {
              key: "federal_withheld",
              label: "Federal Tax Withheld",
              type: "currency",
              description: "Federal income tax your employer withheld from paychecks.",
              source: "W-2 Box 2.",
            },
            {
              key: "state_withheld",
              label: "State Tax Withheld",
              type: "currency",
              description: "State income tax withheld.",
              source: "W-2 Box 17.",
            },
            {
              key: "hsa_contributions_through_payroll",
              label: "HSA via Payroll",
              type: "currency",
              description: "HSA contributions made through pre-tax payroll deductions. These are excluded from Box 1 wages and are not deducted again on Schedule 1.",
              source: "W-2 Box 12, Code W.",
            },
            {
              key: "retirement_contributions_through_payroll",
              label: "Retirement Contributions",
              type: "currency",
              description: "Pre-tax 401(k), 403(b), or SIMPLE IRA contributions deducted from your paycheck.",
              source: "W-2 Box 12, Code D (401k), E (403b), or S (SIMPLE).",
            },
            {
              key: "dependent_care_fsa",
              label: "Dependent Care FSA",
              type: "currency",
              description: "Employer-provided dependent care FSA contributions. Up to $5,000 is excludable from income.",
              source: "W-2 Box 10.",
            },
          ],
        },
      ],
    },
    {
      label: "Self-Employment",
      type: "list",
      key: "self_employment",
      addLabel: "Add Business",
      itemLabel: "Business",
      description: "Each self-employment activity or business. Matches entries in the Businesses section.",
      source: "Schedule C, Schedule E (partnerships/S-corps), or your profit & loss statement.",
      itemGroups: [
        {
          label: "Business Income",
          fields: [
            {
              key: "business_name",
              label: "Business Name",
              type: "text",
              description: "Must match the name in your Businesses section for cross-referencing.",
              source: "Your business name on Schedule C or K-1.",
            },
            {
              key: "gross_revenue",
              label: "Gross Revenue",
              type: "currency",
              description: "Total revenue before any deductions.",
              source: "Schedule C Line 1 (gross receipts) or K-1 Box 1.",
            },
            {
              key: "net_profit",
              label: "Net Profit",
              type: "currency",
              description: "Revenue minus business expenses. This flows to Schedule SE for self-employment tax.",
              source: "Schedule C Line 31 (net profit/loss).",
              calculate: "Gross revenue − cost of goods sold − business expenses = net profit.",
            },
            {
              key: "se_tax_estimated",
              label: "SE Tax (Estimated)",
              type: "currency",
              description: "Self-employment tax owed on net profit. Approximately 15.3% on the first $176,100 and 2.9% above that.",
              source: "Schedule SE. You can estimate as net profit × 0.9235 × 0.153.",
              calculate: "Net profit × 92.35% × 15.3% = approximate SE tax (for income under SE wage base).",
            },
          ],
        },
      ],
    },
    {
      label: "Rental Income",
      type: "list",
      key: "rental_income",
      addLabel: "Add Rental Property",
      itemLabel: "Rental Property",
      description: "Each rental property you own. Matches entries in the Real Estate section.",
      source: "Schedule E or your rental ledger.",
      itemGroups: [
        {
          label: "Rental Amounts",
          fields: [
            {
              key: "property_address",
              label: "Property Address",
              type: "text",
              description: "Must match the address in your Real Estate section.",
              source: "Your lease agreement or property records.",
            },
            {
              key: "gross_rents",
              label: "Gross Rents",
              type: "currency",
              description: "Total rent collected before any expenses.",
              source: "Schedule E Part I, Line 3.",
            },
            {
              key: "net_income_loss",
              label: "Net Income / (Loss)",
              type: "currency",
              description: "Rental income after all deductible expenses including depreciation. Negative means a passive loss.",
              source: "Schedule E Part I, Line 21 or 22.",
            },
          ],
        },
      ],
    },
    {
      label: "Investment Income",
      path: "investment_income",
      fields: [
        {
          key: "qualified_dividends",
          label: "Qualified Dividends",
          type: "currency",
          description: "Dividends taxed at the lower long-term capital gains rates (0%, 15%, or 20%).",
          source: "Form 1099-DIV Box 1b. Sum all 1099-DIVs you receive.",
        },
        {
          key: "ordinary_dividends",
          label: "Ordinary Dividends",
          type: "currency",
          description: "Total dividends including qualified. Must be ≥ qualified dividends.",
          source: "Form 1099-DIV Box 1a.",
        },
        {
          key: "interest",
          label: "Taxable Interest",
          type: "currency",
          description: "Interest income from bank accounts, CDs, and taxable bonds.",
          source: "Form 1099-INT Box 1. Sum all 1099-INTs.",
        },
        {
          key: "short_term_capital_gains",
          label: "Short-Term Capital Gains",
          type: "currency",
          description: "Gains from assets held 1 year or less. Taxed as ordinary income.",
          source: "Form 1099-B or Schedule D. Sum all short-term net gains.",
        },
        {
          key: "long_term_capital_gains",
          label: "Long-Term Capital Gains",
          type: "currency",
          description: "Gains from assets held more than 1 year. Taxed at preferential 0%, 15%, or 20% rates.",
          source: "Form 1099-B or Schedule D. Sum all long-term net gains.",
        },
      ],
    },
    {
      label: "Retirement Distributions",
      path: "retirement_distributions",
      fields: [
        {
          key: "traditional_ira",
          label: "Traditional IRA Distributions",
          type: "currency",
          description: "Taxable distributions from traditional IRAs. If you have non-deductible basis (Form 8606), only a portion is taxable.",
          source: "Form 1099-R Box 2a (taxable amount).",
        },
        {
          key: "roth_ira",
          label: "Roth IRA Distributions",
          type: "currency",
          description: "Distributions from Roth IRAs. Qualified distributions are tax-free; early/non-qualified distributions may be taxable.",
          source: "Form 1099-R. Qualified Roth distributions show $0 in Box 2a.",
        },
        {
          key: "401k",
          label: "401(k) / 403(b) Distributions",
          type: "currency",
          description: "Distributions from employer plans. Generally fully taxable unless Roth after-tax contributions were made.",
          source: "Form 1099-R Box 2a.",
        },
        {
          key: "pension",
          label: "Pension / Annuity",
          type: "currency",
          description: "Taxable pension income. If you contributed after-tax money, use the Simplified Method to determine the taxable portion.",
          source: "Form 1099-R or pension statement.",
        },
        {
          key: "required_minimum_distribution",
          label: "RMD Required?",
          type: "boolean",
          description: "Whether you are subject to Required Minimum Distributions (age 73+ in 2025). RMDs are taxable and cannot be rolled over.",
          source: "RMDs begin at age 73. Your IRA custodian will calculate the required amount.",
        },
      ],
    },
    {
      label: "Social Security",
      path: "social_security",
      fields: [
        {
          key: "gross_benefits",
          label: "Gross SS Benefits",
          type: "currency",
          description: "Total Social Security benefits received before any Medicare deductions.",
          source: "Form SSA-1099 Box 5 (net benefits). Add back Medicare premiums withheld if desired for gross.",
        },
        {
          key: "taxable_portion",
          label: "Taxable Portion",
          type: "currency",
          description: "The taxable portion of your SS benefits (0–85% depending on combined income). The scanner can estimate this.",
          source: "IRS Publication 915 worksheet, or your prior-year Schedule 1 Line 6b.",
          calculate: "Taxable SS = 0–85% of gross benefits based on combined income (AGI + non-taxable interest + half of SS benefits).",
        },
      ],
    },
    {
      label: "Passive Income (K-1)",
      path: "passive_income",
      fields: [
        {
          key: "k1_ordinary",
          label: "K-1 Ordinary Income",
          type: "currency",
          description: "Ordinary income from partnerships, S corporations, or trusts passed through on Schedule K-1.",
          source: "Schedule K-1 Box 1 (ordinary income/loss).",
        },
        {
          key: "k1_rental",
          label: "K-1 Rental Income",
          type: "currency",
          description: "Rental income passed through from a partnership or S-corp.",
          source: "Schedule K-1 Box 2.",
        },
        {
          key: "k1_guaranteed_payments",
          label: "Guaranteed Payments",
          type: "currency",
          description: "Payments to a partner for services, regardless of partnership income. Subject to self-employment tax.",
          source: "Schedule K-1 Box 4.",
        },
      ],
    },
    {
      label: "Other Income",
      path: "other_income",
      fields: [
        {
          key: "alimony_received",
          label: "Alimony Received",
          type: "currency",
          description: "Alimony received under pre-2019 divorce agreements is taxable income. Post-2018 agreements: not taxable.",
          source: "Your divorce or separation agreement date determines whether it's taxable.",
        },
        {
          key: "gambling_winnings",
          label: "Gambling Winnings",
          type: "currency",
          description: "Taxable gambling winnings. Losses are deductible only as an itemized deduction up to winnings.",
          source: "Form W-2G from casinos, or your own records.",
        },
        {
          key: "other_amount",
          label: "Other Income Amount",
          type: "currency",
          description: "Other taxable income not captured elsewhere (prizes, awards, cancellation of debt, etc.).",
          source: "Any 1099 or income statement for amounts not covered above.",
        },
        {
          key: "other_description",
          label: "Other Income Description",
          type: "text",
          description: "Brief description of the other income type.",
          source: "Your own description.",
        },
      ],
    },
    {
      label: "Adjustments to Income",
      path: "adjustments_to_income",
      fields: [
        {
          key: "student_loan_interest",
          label: "Student Loan Interest",
          type: "currency",
          description: "Interest paid on qualified student loans. Up to $2,500 deductible (phases out at higher AGI).",
          source: "Form 1098-E from your loan servicer.",
        },
        {
          key: "educator_expenses",
          label: "Educator Expenses",
          type: "currency",
          description: "K-12 teachers can deduct up to $300 ($600 if both spouses are educators) for classroom supplies.",
          source: "Your own receipts for classroom supplies and professional development.",
        },
        {
          key: "hsa_contributions_outside_payroll",
          label: "HSA Contributions (Direct)",
          type: "currency",
          description: "HSA contributions you made directly (not through payroll). Deductible on Schedule 1.",
          source: "Form 5498-SA or your HSA account statements.",
        },
        {
          key: "self_employed_health_insurance",
          label: "SE Health Insurance",
          type: "currency",
          description: "Health, dental, and long-term care insurance premiums paid for yourself and family as a self-employed person. Deductible above the line.",
          source: "Your insurance premium statements. Must not exceed your business net profit.",
        },
        {
          key: "self_employed_se_tax_deduction",
          label: "SE Tax Deduction",
          type: "currency",
          description: "You can deduct half of your self-employment tax as an above-the-line adjustment. The scanner calculates this automatically.",
          source: "Schedule SE Line 13. Equals SE tax ÷ 2.",
        },
        {
          key: "ira_deduction",
          label: "IRA Deduction",
          type: "currency",
          description: "Deductible traditional IRA contributions (subject to income limits if you or a spouse have an employer plan).",
          source: "Your IRA contribution records. Deductibility depends on your AGI and retirement plan access.",
        },
        {
          key: "alimony_paid",
          label: "Alimony Paid",
          type: "currency",
          description: "Alimony paid under pre-2019 agreements is deductible. Post-2018 agreements: not deductible.",
          source: "Your divorce agreement date and payment records.",
        },
      ],
    },
    {
      label: "Notes",
      fields: [
        {
          key: "notes",
          label: "Notes",
          type: "textarea",
          placeholder: "Income notes…",
          description: "Notes about unusual income items or expected changes.",
          source: "Your own notes.",
        },
      ],
    },
  ],
};
