export const schema = {
  label: "Income",
  description: "All income sources and above-the-line adjustments. Accurate income data is the foundation of every opportunity calculation.",
  groups: [
    {
      label: "W-2 Employment",
      type: "list",
      key: "w2_employment",
      addLabel: "Add W-2 Employer",
      itemLabel: "W-2 Job",
      description: "Each employer from which you received a W-2 this year.",
      source: "Your W-2 forms. Employers must mail W-2s by January 31.",
      itemGroups: [
        {
          label: "W-2 Details",
          fields: [
            {
              key: "employer_name",
              label: "Employer Name",
              type: "text",
              description: "The company name on the W-2.",
              source: "W-2 Box c (Employer's name).",
            },
            {
              key: "employer_ein",
              label: "Employer EIN",
              type: "text",
              placeholder: "XX-XXXXXXX",
              description: "Your employer's federal tax ID number. Used for verification and some state returns.",
              source: "W-2 Box b (Employer identification number).",
            },
            {
              key: "wages",
              label: "Wages (Box 1)",
              type: "currency",
              description: "Taxable wages, tips, and other compensation from this employer.",
              source: "W-2 Box 1.",
            },
            {
              key: "federal_withheld",
              label: "Federal Tax Withheld",
              type: "currency",
              description: "Federal income tax your employer withheld from paychecks.",
              source: "W-2 Box 2.",
            },
            {
              key: "state_withheld",
              label: "State Tax Withheld",
              type: "currency",
              description: "State income tax withheld.",
              source: "W-2 Box 17.",
            },
            {
              key: "hsa_contributions_through_payroll",
              label: "HSA via Payroll",
              type: "currency",
              description: "HSA contributions made through pre-tax payroll deductions. These are excluded from Box 1 wages and are not deducted again on Schedule 1.",
              source: "W-2 Box 12, Code W.",
            },
            {
              key: "retirement_contributions_through_payroll",
              label: "Retirement Contributions",
              type: "currency",
              description: "Pre-tax 401(k), 403(b), or SIMPLE IRA contributions deducted from your paycheck.",
              source: "W-2 Box 12, Code D (401k), E (403b), or S (SIMPLE).",
            },
            {
              key: "dependent_care_fsa",
              label: "Dependent Care FSA",
              type: "currency",
              description: "Employer-provided dependent care FSA contributions. Up to $5,000 is excludable from income.",
              source: "W-2 Box 10.",
            },
          ],
        },
      ],
    },
    {
      label: "Self-Employment",
      type: "list",
      key: "self_employment",
      addLabel: "Add Business",
      itemLabel: "Business",
      description: "Each self-employment activity or business. Matches entries in the Businesses section.",
      source: "Schedule C, Schedule E (partnerships/S-corps), or your profit & loss statement.",
      itemGroups: [
        {
          label: "Business Income",
          fields: [
            {
              key: "business_name",
              label: "Business Name",
              type: "text",
              description: "Must match the name in your Businesses section for cross-referencing.",
              source: "Your business name on Schedule C or K-1.",
            },
            {
              key: "gross_revenue",
              label: "Gross Revenue",
              type: "currency",
              description: "Total revenue before any deductions.",
              source: "Schedule C Line 1 (gross receipts) or K-1 Box 1.",
            },
            {
              key: "net_profit",
              label: "Net Profit",
              type: "currency",
              description: "Revenue minus business expenses. This flows to Schedule SE for self-employment tax.",
              source: "Schedule C Line 31 (net profit/loss).",
              calculate: "Gross revenue − cost of goods sold − business expenses = net profit.",
            },
            {
              key: "se_tax_estimated",
              label: "SE Tax (Estimated)",
              type: "currency",
              description: "Self-employment tax owed on net profit. Approximately 15.3% on the first $176,100 and 2.9% above that.",
              source: "Schedule SE. You can estimate as net profit × 0.9235 × 0.153.",
              calculate: "Net profit × 92.35% × 15.3% = approximate SE tax (for income under SE wage base).",
            },
          ],
        },
      ],
    },
    {
      label: "Rental Income",
      type: "list",
      key: "rental_income",
      addLabel: "Add Rental Property",
      itemLabel: "Rental Property",
      description: "Each rental property you own. Matches entries in the Real Estate section.",
      source: "Schedule E or your rental ledger.",
      itemGroups: [
        {
          label: "Rental Amounts",
          fields: [
            {
              key: "property_address",
              label: "Property Address",
              type: "text",
              description: "Must match the address in your Real Estate section.",
              source: "Your lease agreement or property records.",
            },
            {
              key: "gross_rents",
              label: "Gross Rents",
              type: "currency",
              description: "Total rent collected before any expenses.",
              source: "Schedule E Part I, Line 3.",
            },
            {
              key: "net_income_loss",
              label: "Net Income / (Loss)",
              type: "currency",
              description: "Rental income after all deductible expenses including depreciation. Negative means a passive loss.",
              source: "Schedule E Part I, Line 21 or 22.",
            },
          ],
        },
      ],
    },
    {
      label: "Investment Income",
      path: "investment_income",
      fields: [
        {
          key: "qualified_dividends",
          label: "Qualified Dividends",
          type: "currency",
          description: "Dividends taxed at the lower long-term capital gains rates (0%, 15%, or 20%).",
          source: "Form 1099-DIV Box 1b. Sum all 1099-DIVs you receive.",
        },
        {
          key: "ordinary_dividends",
          label: "Ordinary Dividends",
          type: "currency",
          description: "Total dividends including qualified. Must be ≥ qualified dividends.",
          source: "Form 1099-DIV Box 1a.",
        },
        {
          key: "interest",
          label: "Taxable Interest",
          type: "currency",
          description: "Interest income from bank accounts, CDs, and taxable bonds.",
          source: "Form 1099-INT Box 1. Sum all 1099-INTs.",
        },
        {
          key: "short_term_capital_gains",
          label: "Short-Term Capital Gains",
          type: "currency",
          description: "Gains from assets held 1 year or less. Taxed as ordinary income.",
          source: "Form 1099-B or Schedule D. Sum all short-term net gains.",
        },
        {
          key: "long_term_capital_gains",
          label: "Long-Term Capital Gains",
          type: "currency",
          description: "Gains from assets held more than 1 year. Taxed at preferential 0%, 15%, or 20% rates.",
          source: "Form 1099-B or Schedule D. Sum all long-term net gains.",
        },
      ],
    },
    {
      label: "Foreign Accounts & Special Elections",
      path: "investment_income",
      advanced: true,
      fields: [
        {
          key: "schedule_d_not_required",
          label: "Schedule D Not Required",
          type: "boolean",
          description: "Check if you have capital gains but are not required to attach Schedule D. This applies when your only capital gain source is Box 2a of Form 1099-DIV (capital gain distributions) and you don't have any capital gains from sales or exchanges. Triggers Form 1040 Line 7b checkbox.",
          source: "Form 1040 Line 7b. Check the Schedule D instructions — if you received Form 1099-DIV Box 2a distributions but made no sales requiring Schedule D, you may qualify.",
        },
        {
          key: "child_capital_gain_included",
          label: "Includes Child's Capital Gain",
          type: "boolean",
          description: "Check if Line 7a (capital gain or loss) includes your child's capital gain or loss that you elected to report on your return using Form 8814 (Parents' Election to Report Child's Interest and Dividends). Triggers the second Form 1040 Line 7b checkbox.",
          source: "Form 1040 Line 7b. Only if you filed Form 8814 to include a child's unearned income on your return instead of the child filing a separate return.",
        },
        {
          key: "foreign_financial_account",
          label: "Foreign Financial Account?",
          type: "boolean",
          description: "Did you have a financial interest in or signature authority over a financial account in a foreign country at any time during the year? Required on Schedule B Part III Line 7a. If total foreign accounts exceeded $10,000, you may also need to file FinCEN Form 114 (FBAR) by April 15.",
          source: "Schedule B Part III, Line 7a. Answer Yes if you had a bank account, brokerage, or other financial account in a foreign country, even if no income was earned.",
        },
        {
          key: "foreign_account_country",
          label: "Foreign Account Country",
          type: "text",
          description: "If you answered Yes to the foreign financial account question, enter the name of the foreign country where the account is held. Schedule B Part III, Line 7b.",
          source: "Schedule B Part III, Line 7b. Enter the country name (e.g., 'Canada', 'United Kingdom').",
        },
        {
          key: "foreign_trust",
          label: "Foreign Trust?",
          type: "boolean",
          description: "Were you the grantor of or transferor to a foreign trust, or did you receive distributions from a foreign trust? Schedule B Part III, Line 8. Additional reporting (Forms 3520/3520-A) may be required.",
          source: "Schedule B Part III, Line 8. Answer Yes if you created, contributed to, or benefited from a foreign trust.",
        },
      ],
    },
    {
      label: "Retirement Distributions",
      path: "retirement_distributions",
      fields: [
        {
          key: "traditional_ira",
          label: "Traditional IRA Distributions",
          type: "currency",
          description: "Taxable distributions from traditional IRAs. If you have non-deductible basis (Form 8606), only a portion is taxable.",
          source: "Form 1099-R Box 2a (taxable amount).",
        },
        {
          key: "roth_ira",
          label: "Roth IRA Distributions",
          type: "currency",
          description: "Distributions from Roth IRAs. Qualified distributions are tax-free; early/non-qualified distributions may be taxable.",
          source: "Form 1099-R. Qualified Roth distributions show $0 in Box 2a.",
        },
        {
          key: "401k",
          label: "401(k) / 403(b) Distributions",
          type: "currency",
          description: "Distributions from employer plans. Generally fully taxable unless Roth after-tax contributions were made.",
          source: "Form 1099-R Box 2a.",
        },
        {
          key: "pension",
          label: "Pension / Annuity",
          type: "currency",
          description: "Taxable pension income. If you contributed after-tax money, use the Simplified Method to determine the taxable portion.",
          source: "Form 1099-R or pension statement.",
        },
        {
          key: "required_minimum_distribution",
          label: "RMD Required?",
          type: "boolean",
          description: "Whether you are subject to Required Minimum Distributions (age 73+ in 2025). RMDs are taxable and cannot be rolled over.",
          source: "RMDs begin at age 73. Your IRA custodian will calculate the required amount.",
        },
        {
          key: "ira_rollover",
          label: "IRA Distribution was a Rollover",
          type: "boolean",
          description: "Check if the IRA distribution on Line 4a was rolled over into another IRA or retirement plan and is therefore not taxable. The rollover amount should NOT be included in the taxable amount (Line 4b). Triggers the 'Rollover' checkbox on Form 1040 Line 4c.",
          source: "Form 1099-R Box 7 rollover code (G, H, etc.). If you rolled over a distribution within 60 days, the taxable amount in Box 2a should be $0.",
        },
        {
          key: "pension_rollover",
          label: "Pension/Annuity was a Rollover",
          type: "boolean",
          description: "Check if the pension or annuity distribution on Line 5a was rolled over and is not taxable. Triggers the 'Rollover' checkbox on Form 1040 Line 5c.",
          source: "Form 1099-R Box 7 rollover code. The taxable amount (Box 2a / Line 5b) should be $0 for a full rollover.",
        },
      ],
    },
    {
      label: "Social Security",
      path: "social_security",
      fields: [
        {
          key: "gross_benefits",
          label: "Gross SS Benefits",
          type: "currency",
          description: "Total Social Security benefits received before any Medicare deductions.",
          source: "Form SSA-1099 Box 5 (net benefits). Add back Medicare premiums withheld if desired for gross.",
        },
        {
          key: "taxable_portion",
          label: "Taxable Portion",
          type: "currency",
          description: "The taxable portion of your SS benefits (0–85% depending on combined income). The scanner can estimate this.",
          source: "IRS Publication 915 worksheet, or your prior-year Schedule 1 Line 6b.",
          calculate: "Taxable SS = 0–85% of gross benefits based on combined income (AGI + non-taxable interest + half of SS benefits).",
        },
        {
          key: "lump_sum_election",
          label: "Lump-Sum Election (§86(e))",
          type: "boolean",
          description: "Check if you elect to use the lump-sum election method to compute tax on Social Security benefits received in a lump sum that covers an earlier year. This alternative calculation can reduce your tax if benefits accumulated over multiple years are paid at once. Triggers Form 1040 Line 6c checkbox.",
          source: "Form 1040 Line 6c. Only applicable if you received SS benefits in a lump sum covering prior years. See IRS Publication 915 for the election worksheet.",
        },
      ],
    },
    {
      label: "Passive Income (K-1)",
      path: "passive_income",
      fields: [
        {
          key: "k1_ordinary",
          label: "K-1 Ordinary Income",
          type: "currency",
          description: "Ordinary income from partnerships, S corporations, or trusts passed through on Schedule K-1.",
          source: "Schedule K-1 Box 1 (ordinary income/loss).",
        },
        {
          key: "k1_rental",
          label: "K-1 Rental Income",
          type: "currency",
          description: "Rental income passed through from a partnership or S-corp.",
          source: "Schedule K-1 Box 2.",
        },
        {
          key: "k1_guaranteed_payments",
          label: "Guaranteed Payments",
          type: "currency",
          description: "Payments to a partner for services, regardless of partnership income. Subject to self-employment tax.",
          source: "Schedule K-1 Box 4.",
        },
      ],
    },
    {
      label: "Other Income",
      path: "other_income",
      fields: [
        {
          key: "taxable_refunds",
          label: "State/Local Tax Refunds",
          type: "currency",
          description: "Taxable portion of state and local income tax refunds, credits, or offsets received this year. Only taxable if you claimed the taxes as an itemized deduction and received a tax benefit. Goes on Schedule 1 Line 1.",
          source: "Form 1099-G Box 2 from your state tax authority.",
        },
        {
          key: "unemployment_compensation",
          label: "Unemployment Compensation",
          type: "currency",
          description: "All unemployment compensation is fully taxable. Goes on Schedule 1 Line 7.",
          source: "Form 1099-G Box 1 from your state unemployment office.",
        },
        {
          key: "alimony_received",
          label: "Alimony Received",
          type: "currency",
          description: "Alimony received under pre-2019 divorce agreements is taxable income. Post-2018 agreements: not taxable. Goes on Schedule 1 Line 2a.",
          source: "Your divorce or separation agreement date determines whether it's taxable.",
        },
        {
          key: "alimony_date_of_divorce",
          label: "Date of Divorce / Separation Agreement",
          type: "text",
          placeholder: "MM/DD/YYYY",
          description: "Date of the most recent divorce decree or separation agreement. Required on Schedule 1 Line 2b if you received alimony. Determines whether alimony is taxable (pre-2019) or not (post-2018).",
          source: "Your divorce or separation agreement.",
        },
      ],
    },
    {
      label: "Less Common Income",
      path: "other_income",
      advanced: true,
      fields: [
        {
          key: "farm_income",
          label: "Farm Income / (Loss)",
          type: "currency",
          description: "Net farm income or loss from Schedule F. Goes on Schedule 1 Line 6.",
          source: "Schedule F Line 34 (net farm profit or loss).",
        },
        {
          key: "net_operating_loss",
          label: "Net Operating Loss (NOL)",
          type: "currency",
          description: "Prior-year net operating loss deduction carried forward or carried back. Enter as a negative number. Goes on Schedule 1 Line 8a.",
          source: "Your prior-year Schedule 1 or tax records. Requires Form 1045 or amended return to carry back.",
        },
        {
          key: "gambling_winnings",
          label: "Gambling Winnings",
          type: "currency",
          description: "Taxable gambling winnings. Losses are deductible only as an itemized deduction up to winnings. Goes on Schedule 1 Line 8b.",
          source: "Form W-2G from casinos, or your own records.",
        },
        {
          key: "canceled_debt",
          label: "Canceled / Forgiven Debt",
          type: "currency",
          description: "Debt forgiven by a lender is generally taxable income. Exclusions may apply for insolvency or bankruptcy. Goes on Schedule 1 Line 8c.",
          source: "Form 1099-C from the lender.",
        },
        {
          key: "prizes_awards",
          label: "Prizes & Awards",
          type: "currency",
          description: "Taxable prizes, awards, and contest winnings. Goes on Schedule 1 Line 8z (Other income).",
          source: "Form 1099-MISC box 3, or Form 1099-NEC.",
        },
        {
          key: "other_amount",
          label: "Other Income Amount",
          type: "currency",
          description: "Other taxable income not captured by any category above. Goes on Schedule 1 Line 8z.",
          source: "Any 1099 or income statement for amounts not covered above.",
        },
        {
          key: "other_description",
          label: "Other Income Description",
          type: "text",
          description: "Brief description of the other income type for Line 8z.",
          source: "Your own description.",
        },
      ],
    },
    {
      label: "Adjustments to Income",
      path: "adjustments_to_income",
      fields: [
        {
          key: "educator_expenses",
          label: "Educator Expenses",
          type: "currency",
          description: "K-12 teachers can deduct up to $300 ($600 if both spouses are educators) for classroom supplies. Schedule 1 Line 11.",
          source: "Your own receipts for classroom supplies and professional development.",
        },
        {
          key: "hsa_contributions_outside_payroll",
          label: "HSA Contributions (Direct)",
          type: "currency",
          description: "HSA contributions you made directly (not through payroll). Deductible on Schedule 1 Line 13.",
          source: "Form 5498-SA or your HSA account statements.",
        },
        {
          key: "ira_deduction",
          label: "IRA Deduction",
          type: "currency",
          description: "Deductible traditional IRA contributions (subject to income limits if you or a spouse have an employer plan). Schedule 1 Line 20.",
          source: "Your IRA contribution records. Deductibility depends on your AGI and retirement plan access.",
        },
        {
          key: "student_loan_interest",
          label: "Student Loan Interest",
          type: "currency",
          description: "Interest paid on qualified student loans. Up to $2,500 deductible (phases out at higher AGI). Schedule 1 Line 21.",
          source: "Form 1098-E from your loan servicer.",
        },
        {
          key: "self_employed_se_tax_deduction",
          label: "SE Tax Deduction",
          type: "currency",
          description: "You can deduct half of your self-employment tax as an above-the-line adjustment. The scanner calculates this automatically. Schedule 1 Line 15.",
          source: "Schedule SE Line 13. Equals SE tax ÷ 2.",
        },
        {
          key: "sep_simple_contributions",
          label: "SEP / SIMPLE / Qualified Plan Contributions",
          type: "currency",
          description: "Contributions to a SEP-IRA, SIMPLE IRA, or other self-employed qualified retirement plan. Schedule 1 Line 16.",
          source: "Your retirement plan contribution records. SEP limit is 25% of net SE income (up to $70,000 for 2025).",
        },
        {
          key: "self_employed_health_insurance",
          label: "SE Health Insurance",
          type: "currency",
          description: "Health, dental, and long-term care insurance premiums paid for yourself and family as a self-employed person. Deductible above the line. Schedule 1 Line 17.",
          source: "Your insurance premium statements. Must not exceed your business net profit.",
        },
      ],
    },
    {
      label: "Less Common Adjustments",
      path: "adjustments_to_income",
      advanced: true,
      fields: [
        {
          key: "moving_expenses_military",
          label: "Military Moving Expenses",
          type: "currency",
          description: "Moving expenses for active-duty military members ordered to a new permanent station. Only members of the Armed Forces on active duty qualify. Schedule 1 Line 14.",
          source: "Form 3903 (Moving Expenses). Only available for military members under orders.",
        },
        {
          key: "alimony_paid",
          label: "Alimony Paid",
          type: "currency",
          description: "Alimony paid under pre-2019 agreements is deductible. Post-2018 agreements: not deductible. Schedule 1 Line 19a.",
          source: "Your divorce agreement date and payment records.",
        },
        {
          key: "alimony_recipient_ssn",
          label: "Alimony Recipient SSN",
          type: "text",
          placeholder: "XXX-XX-XXXX",
          description: "Social Security Number of the person who received the alimony you paid. Required on Schedule 1 Line 19b if you deducted alimony paid.",
          source: "Your ex-spouse's SSN (from prior returns or divorce records).",
        },
        {
          key: "other_adjustments_amount",
          label: "Other Adjustments Amount",
          type: "currency",
          description: "Other above-the-line deductions not covered above (e.g., repayment of prior-year income, certain attorney fees). Goes on Schedule 1 Line 24z.",
          source: "See Schedule 1 instructions for Line 24. Include a description below.",
        },
        {
          key: "other_adjustments_description",
          label: "Other Adjustments Description",
          type: "text",
          description: "Brief description of the other adjustment on Line 24z.",
          source: "Your own description.",
        },
      ],
    },
    {
      label: "Uncommon Earned Income",
      path: "other_wages",
      advanced: true,
      fields: [
        {
          key: "household_employee_wages",
          label: "Household Employee Wages (Line 1b)",
          type: "currency",
          description: "Wages you received as a household employee (e.g., nanny, housekeeper) that your employer did NOT report on a W-2. Goes on Form 1040 Line 1b.",
          source: "If your employer failed to give you a W-2, report the cash wages here. Schedule H is filed by the employer, not you.",
        },
        {
          key: "tip_income_unreported",
          label: "Tip Income Not Reported on W-2 (Line 1c)",
          type: "currency",
          description: "Tips you received but did not report to your employer, or tips allocated to you by your employer but not on your W-2 (Form 4137). Goes on Form 1040 Line 1c.",
          source: "Form 4137 Line 6. Common for servers and other tip-earning workers whose W-2 Box 1 did not include all tips.",
        },
        {
          key: "medicaid_waiver_payments",
          label: "Medicaid Waiver Payments (Line 1d)",
          type: "currency",
          description: "Certain Medicaid waiver payments that you elected to include in earned income under IRS Notice 2014-7 (e.g., payments for caring for a disabled family member at home). Goes on Form 1040 Line 1d.",
          source: "IRS Notice 2014-7. Most home care providers under a Medicaid waiver program can exclude these; enter only if electing to include for EITC purposes.",
        },
        {
          key: "other_earned_income",
          label: "Other Earned Income (Line 1h)",
          type: "currency",
          description: "Any other earned income not captured above — such as taxable disability payments before minimum retirement age, income from an Indian tribal government, or other unusual earned income. Goes on Form 1040 Line 1h.",
          source: "Form 1040 Line 1h instructions. Rarely needed; most earned income is covered by W-2 wages or the fields above.",
        },
      ],
    },
    {
      label: "Notes",
      fields: [
        {
          key: "notes",
          label: "Notes",
          type: "textarea",
          placeholder: "Income notes…",
          description: "Notes about unusual income items or expected changes.",
          source: "Your own notes.",
        },
      ],
    },
  ],
};
