export const schema = {
  label: "Investments",
  description: "Taxable brokerage accounts, capital gains, tax-loss harvesting opportunities, 529 plans, opportunity zone investments, and cryptocurrency.",
  groups: [
    {
      label: "Taxable Accounts",
      type: "list",
      key: "taxable_accounts",
      addLabel: "Add Account",
      itemLabel: "Account",
      description: "Each taxable brokerage or investment account (not retirement accounts — those go in Retirement).",
      source: "Your brokerage statements (Fidelity, Schwab, Vanguard, etc.).",
      itemGroups: [
        {
          label: "Account Details",
          fields: [
            {
              key: "account_name",
              label: "Account Name",
              type: "text",
              placeholder: "e.g., Fidelity Brokerage",
              description: "A name you use to identify this account.",
              source: "Your own label or the account title on your statements.",
            },
            {
              key: "custodian",
              label: "Custodian",
              type: "text",
              placeholder: "e.g., Fidelity, Schwab",
              description: "The brokerage or financial institution holding the account.",
              source: "Your account statements.",
            },
            {
              key: "account_type",
              label: "Account Type",
              type: "select",
              options: [
                { value: "individual", label: "Individual" },
                { value: "joint", label: "Joint (with spouse)" },
                { value: "trust", label: "Trust" },
                { value: "custodial", label: "Custodial (UGMA/UTMA)" },
              ],
              description: "The legal ownership structure of the account.",
              source: "Your account title on your brokerage statement.",
            },
            {
              key: "approximate_value",
              label: "Approximate Value",
              type: "currency",
              description: "Current estimated market value. Used for planning, not filing.",
              source: "Your brokerage account balance.",
            },
          ],
        },
      ],
    },
    {
      label: "Holdings",
      path: "holdings",
      fields: [
        {
          key: "individual_stocks",
          label: "Individual Stocks",
          type: "boolean",
          description: "Whether you hold individual stocks. Creates potential for tax-loss harvesting and wash-sale concerns.",
          source: "Your brokerage positions.",
        },
        {
          key: "mutual_funds",
          label: "Mutual Funds",
          type: "boolean",
          description: "Whether you hold mutual funds. Year-end capital gain distributions are taxable even if reinvested.",
          source: "Your brokerage positions.",
        },
        {
          key: "etfs",
          label: "ETFs",
          type: "boolean",
          description: "Exchange-Traded Funds. Generally more tax-efficient than mutual funds due to in-kind redemptions.",
          source: "Your brokerage positions.",
        },
        {
          key: "bonds",
          label: "Bonds / Fixed Income",
          type: "boolean",
          description: "Whether you hold taxable bonds. Interest is generally ordinary income. Municipal bond interest is typically tax-free.",
          source: "Your brokerage positions.",
        },
        {
          key: "crypto",
          label: "Cryptocurrency",
          type: "boolean",
          description: "Whether you hold or trade cryptocurrency. Each trade, sale, or exchange is a taxable event.",
          source: "Your exchange account (Coinbase, Kraken, etc.).",
        },
        {
          key: "options",
          label: "Options",
          type: "boolean",
          description: "Whether you trade options. Options gains/losses are reported on Form 1099-B.",
          source: "Your brokerage account.",
        },
      ],
    },
    {
      label: "Realized Gains & Losses",
      path: "realized_gains_losses_this_year",
      fields: [
        {
          key: "short_term_gains",
          label: "Short-Term Gains",
          type: "currency",
          description: "Gains from assets sold after holding 1 year or less. Taxed as ordinary income.",
          source: "Form 1099-B or your brokerage's year-end tax statement. Also on Schedule D.",
        },
        {
          key: "short_term_losses",
          label: "Short-Term Losses",
          type: "currency",
          description: "Losses from short-term sales. Offset short-term gains first, then long-term gains, then up to $3,000 of ordinary income.",
          source: "Form 1099-B or Schedule D.",
        },
        {
          key: "long_term_gains",
          label: "Long-Term Gains",
          type: "currency",
          description: "Gains from assets held more than 1 year. Taxed at 0%, 15%, or 20% depending on income.",
          source: "Form 1099-B or Schedule D.",
        },
        {
          key: "long_term_losses",
          label: "Long-Term Losses",
          type: "currency",
          description: "Losses from long-term sales. Offset long-term gains first, then short-term gains, then up to $3,000 of ordinary income.",
          source: "Form 1099-B or Schedule D.",
        },
      ],
    },
    {
      label: "Unrealized Positions",
      fields: [
        {
          key: "unrealized_gains",
          label: "Unrealized Gains (Approx.)",
          type: "currency",
          description: "Estimated unrealized gains across your taxable accounts. Used to identify tax-loss harvesting opportunities and gift planning.",
          source: "Your brokerage's 'unrealized gain/loss' report.",
        },
        {
          key: "unrealized_losses",
          label: "Unrealized Losses (Approx.)",
          type: "currency",
          description: "Estimated unrealized losses. Selling these generates a loss that can offset gains or reduce ordinary income by up to $3,000/year.",
          source: "Your brokerage's 'unrealized gain/loss' report.",
        },
      ],
    },
    {
      label: "Tax-Loss Harvesting",
      path: "tax_loss_harvesting",
      fields: [
        {
          key: "opportunities_identified",
          label: "Opportunities Identified",
          type: "boolean",
          description: "Whether you or your advisor have identified specific positions with losses worth harvesting this year.",
          source: "Your brokerage's unrealized loss report.",
        },
        {
          key: "wash_sale_risk",
          label: "Wash Sale Risk",
          type: "tristate",
          description: "Whether you have bought substantially identical securities within 30 days before/after a sale at a loss. Wash sales disallow the loss.",
          source: "Review your purchase history. The 30-day window runs both before and after the sale date.",
        },
      ],
    },
    {
      label: "529 Education Plans",
      type: "list",
      key: "529_plans",
      addLabel: "Add 529 Plan",
      itemLabel: "529 Plan",
      description: "Each 529 college savings plan you own.",
      source: "Your 529 plan account statements.",
      itemGroups: [
        {
          label: "529 Details",
          fields: [
            {
              key: "beneficiary",
              label: "Beneficiary",
              type: "text",
              description: "The person whose education the account is intended for.",
              source: "Your 529 account documents.",
            },
            {
              key: "owner",
              label: "Account Owner",
              type: "text",
              description: "The account owner (usually parent or grandparent).",
              source: "Your 529 account documents.",
            },
            {
              key: "state_plan",
              label: "State Plan",
              type: "text",
              placeholder: "e.g., Texas College Savings Plan",
              description: "The state-sponsored plan name. Your home state's plan may offer a state income tax deduction.",
              source: "Your 529 account documents.",
            },
            {
              key: "balance",
              label: "Current Balance",
              type: "currency",
              description: "Current 529 account balance.",
              source: "Your 529 account statement.",
            },
            {
              key: "contributions_this_year",
              label: "Contributions This Year",
              type: "currency",
              description: "Total contributions made this year. May qualify for a state tax deduction (varies by state). Subject to gift tax annual exclusion ($19,000 in 2025).",
              source: "Your contribution records or 529 account history.",
            },
            {
              key: "state_deduction_available",
              label: "State Deduction Available?",
              type: "boolean",
              description: "Whether your state offers a deduction or credit for 529 contributions. About 34 states offer this benefit.",
              source: "Check your state's 529 plan website or your state tax instructions.",
            },
          ],
        },
      ],
    },
    {
      label: "Opportunity Zone Investments",
      type: "list",
      key: "opportunity_zone_investments",
      addLabel: "Add OZ Investment",
      itemLabel: "OZ Investment",
      description: "Qualified Opportunity Fund investments. These provide capital gains deferral and potential exclusion for gains after 10 years.",
      source: "Your QOF investment documents.",
      itemGroups: [
        {
          label: "OZ Investment Details",
          fields: [
            {
              key: "fund_name",
              label: "Fund Name",
              type: "text",
              description: "Name of the Qualified Opportunity Fund.",
              source: "Your subscription agreement or K-1.",
            },
            {
              key: "investment_date",
              label: "Investment Date",
              type: "date",
              description: "Date of investment. Must invest deferred gain within 180 days of the triggering sale.",
              source: "Your investment confirmation.",
            },
            {
              key: "amount_invested",
              label: "Amount Invested",
              type: "currency",
              description: "The amount of deferred capital gain invested in the QOF.",
              source: "Your investment confirmation.",
            },
            {
              key: "original_gain_deferred",
              label: "Original Gain Deferred",
              type: "currency",
              description: "The capital gain deferred by investing in the QOF. This gain is recognized on December 31, 2026 (latest).",
              source: "Form 8997 from prior year or your investment records.",
            },
          ],
        },
      ],
    },
    {
      label: "Cryptocurrency",
      path: "crypto",
      fields: [
        {
          key: "held",
          label: "Holds Crypto",
          type: "boolean",
          description: "Whether you hold any cryptocurrency. Answers 'Yes' to the crypto question on Form 1040.",
          source: "Your exchange accounts or wallet balances.",
        },
        {
          key: "approximate_value",
          label: "Approximate Value",
          type: "currency",
          description: "Current estimated value of all crypto holdings.",
          source: "Your exchange account balance or CoinMarketCap.",
        },
        {
          key: "transactions_this_year",
          label: "Transactions This Year",
          type: "boolean",
          description: "Whether you sold, traded, or exchanged crypto. Each transaction is a taxable event requiring Form 8949 reporting.",
          source: "Your exchange transaction history.",
        },
        {
          key: "staking_rewards",
          label: "Staking Rewards Received",
          type: "boolean",
          description: "Whether you received staking or mining rewards. These are ordinary income when received, taxed at fair market value.",
          source: "Your exchange account or blockchain records.",
        },
      ],
    },
    {
      label: "Notes",
      fields: [
        {
          key: "notes",
          label: "Notes",
          type: "textarea",
          placeholder: "Investment notes…",
          description: "Notes about your investment strategy, pending sales, or tax planning considerations.",
          source: "Your own notes.",
        },
      ],
    },
  ],
};
