export const schema = {
  label: "Real Estate",
  description: "Each real property you own, including your primary home, second homes, and rental properties. Used for mortgage interest, depreciation, rental loss, and §121 exclusion calculations.",
  groups: [
    {
      label: "Properties",
      type: "list",
      key: "properties",
      addLabel: "Add Property",
      itemLabel: "Property",
      description: "Add one entry per property. The address here must match your Income section rental entries.",
      source: "Your mortgage statements, property tax bills, and closing disclosure.",
      itemGroups: [
        {
          label: "Property Identity",
          fields: [
            {
              key: "address",
              label: "Address",
              type: "text",
              placeholder: "123 Main St, Austin TX 78701",
              description: "Full property address. Must match the address in your Income section rental entries.",
              source: "Your deed, mortgage statement, or property tax bill.",
            },
            {
              key: "property_type",
              label: "Property Type",
              type: "select",
              options: [
                { value: "primary_residence", label: "Primary Residence" },
                { value: "second_home", label: "Second Home / Vacation Home" },
                { value: "rental_residential", label: "Rental — Residential" },
                { value: "rental_commercial", label: "Rental — Commercial" },
                { value: "land", label: "Land (no structure)" },
                { value: "mixed_use", label: "Mixed Use" },
              ],
              description: "How the property is used. Rental properties generate depreciation deductions; primary residences may qualify for the §121 exclusion on sale.",
              source: "How you primarily use the property.",
            },
            {
              key: "ownership_type",
              label: "Ownership Type",
              type: "select",
              options: [
                { value: "individual", label: "Individual" },
                { value: "llc", label: "LLC" },
                { value: "partnership", label: "Partnership" },
                { value: "s_corp", label: "S Corporation" },
                { value: "tenants_in_common", label: "Tenants in Common" },
                { value: "joint", label: "Joint Tenancy / Community Property" },
              ],
              description: "Who holds legal title. Properties in an LLC or S-corp may have different depreciation and sale treatment.",
              source: "Your deed or title insurance policy.",
            },
            {
              key: "ownership_percent",
              label: "Ownership %",
              type: "number",
              placeholder: "100",
              description: "Your percentage ownership if less than 100%. Used to prorate income and deductions.",
              source: "Your operating agreement, deed, or title documents.",
            },
          ],
        },
        {
          label: "Acquisition & Basis",
          path: "acquisition",
          fields: [
            {
              key: "purchase_date",
              label: "Purchase Date",
              type: "date",
              description: "The closing date when you took ownership. Determines the holding period for capital gains purposes.",
              source: "Your closing disclosure (CD) or HUD-1 settlement statement.",
            },
            {
              key: "purchase_price",
              label: "Purchase Price",
              type: "currency",
              description: "The price you paid for the property. The starting point for your cost basis.",
              source: "Your closing disclosure, Line K (purchase price).",
            },
            {
              key: "closing_costs",
              label: "Closing Costs at Purchase",
              type: "currency",
              description: "Settlement charges paid at purchase that are added to your basis (title insurance, recording fees, legal fees). Loan origination fees and prepaid interest are not added to basis.",
              source: "Your closing disclosure, Section A and B charges that you paid.",
            },
            {
              key: "improvements_since_purchase",
              label: "Capital Improvements",
              type: "currency",
              description: "Cost of improvements that add value, prolong life, or adapt the property to new uses (additions, new roof, HVAC). Repairs and maintenance are not improvements.",
              source: "Your receipts and contractor invoices for major work since purchase.",
              calculate: "Sum all capital improvement costs. Routine repairs (patching, painting touch-ups) do not add to basis.",
            },
            {
              key: "current_market_value",
              label: "Current Market Value",
              type: "currency",
              description: "Estimated current fair market value. Used for equity calculations and planning, not tax filing.",
              source: "Recent comparable sales (Zillow, Redfin), a formal appraisal, or your county assessor's value.",
            },
          ],
        },
        {
          label: "Financing",
          path: "financing",
          fields: [
            {
              key: "mortgage_balance",
              label: "Mortgage Balance",
              type: "currency",
              description: "Current outstanding mortgage principal. Used to determine if you are under the $750,000 acquisition debt limit for mortgage interest deduction.",
              source: "Your year-end mortgage statement or loan servicer online portal.",
            },
            {
              key: "mortgage_interest_paid",
              label: "Mortgage Interest Paid",
              type: "currency",
              description: "Total mortgage interest paid this year. Deductible on Schedule A if you itemize (subject to the $750k debt limit for loans after 12/15/2017).",
              source: "Form 1098 Box 1 from your lender.",
            },
            {
              key: "points_paid_this_year",
              label: "Points Paid This Year",
              type: "currency",
              description: "Mortgage points paid at closing on a new purchase are fully deductible in year paid if they meet IRS tests. Refinance points must be amortized.",
              source: "Form 1098 Box 6 or your closing disclosure.",
            },
            {
              key: "property_tax_paid",
              label: "Property Taxes Paid",
              type: "currency",
              description: "Real estate taxes paid during the year. Deductible on Schedule A up to the $10,000 SALT cap (combined with state income tax).",
              source: "Your property tax bills or Form 1098 Box 4.",
            },
            {
              key: "pmi_paid",
              label: "PMI / MIP Paid",
              type: "currency",
              description: "Private mortgage insurance or FHA mortgage insurance premiums. Potentially deductible if Congress extends the provision.",
              source: "Form 1098 Box 5.",
            },
          ],
        },
        {
          label: "Rental Use",
          path: "rental_use",
          fields: [
            {
              key: "rental_days",
              label: "Days Rented",
              type: "number",
              description: "Days the property was actually rented at fair market value this year. If < 15 days, rental income is tax-free and no expenses are deductible.",
              source: "Your rental ledger or platform (Airbnb, VRBO) activity report.",
            },
            {
              key: "personal_use_days",
              label: "Personal Use Days",
              type: "number",
              description: "Days you used the property personally. If personal use > 14 days AND > 10% of rental days, the property is treated as a vacation home with limited loss deductions.",
              source: "Your own records. Days you stayed at the property.",
            },
            {
              key: "gross_rental_income",
              label: "Gross Rental Income",
              type: "currency",
              description: "Total rent received before expenses.",
              source: "Your rental ledger, bank deposits, or platform payout history.",
            },
          ],
        },
        {
          label: "Primary Residence",
          path: "primary_residence",
          fields: [
            {
              key: "years_lived_in",
              label: "Years Lived In",
              type: "number",
              description: "How many years you have lived in the property as your main home.",
              source: "Move-in date vs. today.",
            },
            {
              key: "used_as_primary_for_2_of_last_5",
              label: "Primary for 2 of Last 5 Years?",
              type: "tristate",
              description: "Whether you lived in the home as your primary residence for at least 2 years during the 5 years before sale. This is the use test for the §121 exclusion.",
              source: "Your records of when you lived in the home.",
            },
            {
              key: "section_121_exclusion_available",
              label: "§121 Exclusion Available?",
              type: "tristate",
              description: "Whether you can exclude up to $250,000 ($500,000 if MFJ) of gain on sale. Requires meeting both the ownership test (owned 2+ of last 5 years) and use test (lived there 2+ of last 5 years).",
              source: "IRS Publication 523. The scanner will flag if you qualify.",
            },
          ],
        },
        {
          label: "Special Categories",
          fields: [
            {
              key: "opportunity_zone",
              label: "Opportunity Zone Property",
              type: "boolean",
              description: "Whether the property is in a Qualified Opportunity Zone. OZ investments receive capital gains deferral and potential exclusion if held 10+ years.",
              source: "IRS OZ census tract tool at cims.cdfifund.gov.",
            },
            {
              key: "historic_property",
              label: "Historic Property",
              type: "boolean",
              description: "Whether the property is a certified historic structure. Rehabilitation expenses may qualify for the 20% Historic Tax Credit.",
              source: "National Park Service historic register or your state Historic Preservation Office.",
            },
            {
              key: "notes",
              label: "Notes",
              type: "textarea",
              placeholder: "Property notes…",
              description: "Notes about this property, pending transactions, or planning considerations.",
              source: "Your own notes.",
            },
          ],
        },
      ],
    },
  ],
};
