export const schema = {
  label: "Retirement",
  description: "All retirement accounts and contributions — employer plans, IRAs, and self-employed plans. Used for contribution limit checks, deductibility analysis, and Roth conversion planning.",
  groups: [
    {
      label: "Traditional 401(k) / Roth 401(k)",
      path: "employer_plans.traditional_401k",
      fields: [
        {
          key: "participating",
          label: "Participating in 401(k)",
          type: "boolean",
          description: "Whether you currently contribute to a 401(k) or are eligible to. Having access to a 401(k) affects whether your traditional IRA contributions are deductible.",
          source: "Your pay stub or HR benefits portal.",
        },
        {
          key: "employee_contribution_ytd",
          label: "Employee Contributions YTD",
          type: "currency",
          description: "Your pre-tax (traditional) 401(k) contributions so far this year. 2025 limit is $23,500 ($31,000 if age 50+).",
          source: "Your pay stub YTD 401(k) column, or your 401(k) account website.",
        },
        {
          key: "roth_401k_contributions_ytd",
          label: "Roth 401(k) Contributions YTD",
          type: "currency",
          description: "After-tax Roth 401(k) contributions. Combined with traditional 401(k) contributions, cannot exceed the $23,500 (or $31,000) annual limit.",
          source: "Your 401(k) account website or pay stub.",
        },
        {
          key: "employer_match_percent",
          label: "Employer Match %",
          type: "number",
          placeholder: "50",
          description: "The percentage of your contribution your employer matches (e.g., 50 means 50-cents-per-dollar).",
          source: "Your employer's 401(k) summary plan description or HR.",
        },
        {
          key: "employer_match_cap",
          label: "Match Cap (% of salary)",
          type: "number",
          placeholder: "6",
          description: "The maximum percentage of your salary the employer will match (e.g., 6 means the match applies to your first 6% of salary contributed).",
          source: "Your 401(k) plan documents or HR.",
        },
        {
          key: "roth_401k_option_available",
          label: "Roth 401(k) Option Available",
          type: "boolean",
          description: "Whether your plan offers a Roth 401(k) option (after-tax contributions).",
          source: "Your 401(k) plan documents or HR benefits portal.",
        },
        {
          key: "plan_balance_approx",
          label: "Plan Balance (Approx.)",
          type: "currency",
          description: "Current estimated 401(k) balance. Used for planning, not filing.",
          source: "Your 401(k) account website.",
        },
      ],
    },
    {
      label: "403(b) / 457(b)",
      path: "employer_plans",
      fields: [
        {
          key: "403b_participating",
          label: "403(b) Participating",
          type: "boolean",
          description: "Whether you contribute to a 403(b) (for non-profit, school, hospital employees). Same contribution limits as a 401(k).",
          source: "Your employer HR or pay stub.",
        },
        {
          key: "403b_contribution_ytd",
          label: "403(b) Contributions YTD",
          type: "currency",
          description: "Contributions to your 403(b) this year.",
          source: "Your pay stub or 403(b) account.",
        },
        {
          key: "457b_participating",
          label: "457(b) Participating",
          type: "boolean",
          description: "Whether you contribute to a 457(b) (government employee plan). Unique: you can contribute the full limit to both a 457(b) AND a 401(k)/403(b) in the same year.",
          source: "Your employer HR or pay stub.",
        },
        {
          key: "457b_contribution_ytd",
          label: "457(b) Contributions YTD",
          type: "currency",
          description: "Contributions to your 457(b) this year.",
          source: "Your pay stub or 457(b) account.",
        },
      ],
    },
    {
      label: "Traditional IRA",
      path: "individual_retirement_accounts.traditional_ira",
      fields: [
        {
          key: "contributions_ytd",
          label: "Contributions YTD",
          type: "currency",
          description: "Traditional IRA contributions made this year. 2025 limit is $7,000 ($8,000 if age 50+), combined across all IRAs.",
          source: "Your IRA account statements or contribution receipts.",
        },
        {
          key: "deductible_contributions",
          label: "Deductible Contributions",
          type: "currency",
          description: "The portion that is deductible. Deductibility phases out if you (or spouse) have a workplace retirement plan and your AGI exceeds thresholds (~$79k–$89k single, $126k–$146k MFJ for 2025).",
          source: "IRS Publication 590-A deductibility worksheet, or have your CPA calculate.",
        },
        {
          key: "nondeductible_basis",
          label: "Non-Deductible Basis (Form 8606)",
          type: "currency",
          description: "Total cumulative non-deductible (after-tax) contributions in all traditional IRAs. Tracked on Form 8606. This basis reduces the taxable portion of future distributions.",
          source: "Your Form 8606 from prior returns. Sum all prior non-deductible IRA contributions.",
        },
        {
          key: "rmd_required",
          label: "RMD Required",
          type: "boolean",
          description: "Whether you are subject to Required Minimum Distributions (age 73+ in 2025). RMDs are calculated based on the prior December 31 balance divided by your life expectancy factor.",
          source: "If you turned 73 this year or older. Your IRA custodian will calculate the RMD amount.",
        },
      ],
    },
    {
      label: "Roth IRA",
      path: "individual_retirement_accounts.roth_ira",
      fields: [
        {
          key: "contributions_ytd",
          label: "Contributions YTD",
          type: "currency",
          description: "Roth IRA contributions this year. Combined with traditional IRA, cannot exceed $7,000 ($8,000 if 50+). Roth contributions phase out at $150k–$165k (single) / $236k–$246k (MFJ) for 2025.",
          source: "Your Roth IRA account statements.",
        },
        {
          key: "income_eligible",
          label: "Income Eligible?",
          type: "tristate",
          description: "Whether your income is below the Roth IRA contribution phase-out. Above the limit, use the Backdoor Roth strategy.",
          source: "Check your MAGI against IRS limits. The scanner evaluates this automatically.",
        },
        {
          key: "backdoor_roth_candidate",
          label: "Backdoor Roth Candidate?",
          type: "tristate",
          description: "Whether you should consider the Backdoor Roth: make a non-deductible traditional IRA contribution then convert it. Best when you have no pre-tax IRA balance (avoids pro-rata rule).",
          source: "The scanner evaluates this based on your income and existing IRA balances.",
        },
      ],
    },
    {
      label: "Self-Employed Retirement Plans",
      path: "self_employed_plans",
      fields: [
        {
          key: "sep_ira_established",
          label: "SEP-IRA Established",
          type: "boolean",
          description: "Whether you have a SEP-IRA. Can be opened up to the tax filing deadline (including extensions). 2025 limit: up to 25% of net SE income, max $70,000.",
          source: "Your SEP-IRA account at a brokerage.",
        },
        {
          key: "sep_ira_contributions_ytd",
          label: "SEP-IRA Contributions YTD",
          type: "currency",
          description: "Contributions made to your SEP-IRA this year.",
          source: "Your SEP-IRA account statements.",
        },
        {
          key: "solo_401k_established",
          label: "Solo 401(k) Established",
          type: "boolean",
          description: "Whether you have a Solo 401(k). Must be opened by December 31 of the tax year to make employer contributions. Employee contributions can be made up to filing deadline.",
          source: "Your Solo 401(k) plan document from your brokerage.",
        },
        {
          key: "solo_401k_employee_contributions_ytd",
          label: "Solo 401(k) Employee Contributions",
          type: "currency",
          description: "Your salary-deferral contributions to the Solo 401(k). Limit: $23,500 ($31,000 if 50+) for 2025.",
          source: "Your Solo 401(k) account statements.",
        },
        {
          key: "solo_401k_employer_contributions_ytd",
          label: "Solo 401(k) Employer Contributions",
          type: "currency",
          description: "The 'employer' portion (25% of net SE income). Combined with employee contributions, total cannot exceed $70,000.",
          source: "Your Solo 401(k) account statements.",
          calculate: "Employer contribution ≈ net SE income × 20% (after the SE tax deduction adjustment).",
        },
      ],
    },
    {
      label: "Roth Conversion",
      path: "roth_conversion",
      advanced: true,
      fields: [
        {
          key: "conversions_this_year",
          label: "Roth Conversions This Year",
          type: "boolean",
          description: "Whether you have converted any traditional IRA or 401(k) funds to Roth this year. Converted amounts are taxable income in the year of conversion.",
          source: "Your IRA custodian records. Form 1099-R will be issued for the converted amount.",
        },
        {
          key: "amount_converted",
          label: "Amount Converted",
          type: "currency",
          description: "Total amount converted to Roth this year. Added to your taxable income.",
          source: "Your conversion confirmation or Form 1099-R Box 2a.",
        },
        {
          key: "strategic_roth_conversion_candidate",
          label: "Strategic Conversion Candidate?",
          type: "tristate",
          description: "Whether you are in a lower-income year where partial Roth conversion makes sense (e.g., filling up a lower bracket). The scanner identifies this opportunity.",
          source: "The scanner evaluates this based on your current bracket vs. expected future tax rates.",
        },
      ],
    },
    {
      label: "Notes",
      fields: [
        {
          key: "notes",
          label: "Notes",
          type: "textarea",
          placeholder: "Retirement notes…",
          description: "Notes about your retirement strategy, planned contributions, or conversion plans.",
          source: "Your own notes.",
        },
      ],
    },
  ],
};
